Define on which week days the day types are active
HSLdevcom/jore4-hasura pull request #100
Opened 2022-10-13 09:41 UTC by pallost

We use a switch table for telling on which week days are DAY TYPEs active. Week days are marked with their ISO week day code (1 = Monday, 7 = Sunday). This representation is useful when checking which DAY TYPEs are active on a given OPERATING DAY.

2022-10-17 07:36 UTC, jarkkoka reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jschummer and @pallost)

___
*[`migrations/generic/timetables/1663231564515_timetables_initial/up.sql` line 61 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100#-NEZrUcj7QAINLJWt4x4:-NEZrUckEEvjj8YaCunR:b-xt96rp) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e87a958bb108155c912d41859c9532e9d294e735/migrations/generic/timetables/1663231564515_timetables_initial/up.sql#L61)):*
> ```TSQL
> CREATE TABLE service_calendar.day_type_active_on_day_of_week (
>   day_type_id UUID REFERENCES service_calendar.day_type (day_type_id) NOT NULL,
>   day_of_week INT NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
> ```

I'd like to know the reasoning behind putting this single `day_of_week` property into a separate table instead of introducing it in `service_calendar.day_type` table?



_Code quote:_
```TSQL
day_of_week INT NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
```


<!-- Sent from Reviewable.io -->

2022-10-24 09:07 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @jschummer)

___
*[`migrations/generic/timetables/1663231564515_timetables_initial/up.sql` line 61 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100#-NEZrUcj7QAINLJWt4x4:-NF8EgdMD3HL0_qub-vc:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e87a958bb108155c912d41859c9532e9d294e735/migrations/generic/timetables/1663231564515_timetables_initial/up.sql#L61)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This was solved. Figured out (in Slack) that there is a one-to-many relationship between the tables.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-27 09:33 UTC, jarkkoka reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100)* status: all files reviewed, 1 unresolved discussion (waiting on @jschummer and @pallost)

___
*[`migrations/generic/timetables/1663231564515_timetables_initial/up.sql` line 61 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100#-NFNlkw2B3b9zamCmb8H:-NFNlkw2B3b9zamCmb8I:bbbbkwx) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e87a958bb108155c912d41859c9532e9d294e735/migrations/generic/timetables/1663231564515_timetables_initial/up.sql#L61)):*
> ```TSQL
> CREATE TABLE service_calendar.day_type_active_on_day_of_week (
>   day_type_id UUID REFERENCES service_calendar.day_type (day_type_id) NOT NULL,
>   day_of_week INT NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
> ```

E.g. let's assume we have a day type for Christmas Eve for which an actual day-of-week depends on the year. Is it meant that for such day type we populate an entry into this table for each seven day of week?



_Code quote:_
```TSQL
day_of_week INT NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7)
```


<!-- Sent from Reviewable.io -->

2022-10-27 10:20 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100)* status: all files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @jschummer)

___
*[`migrations/generic/timetables/1663231564515_timetables_initial/up.sql` line 61 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100#-NFNlkw2B3b9zamCmb8H:-NFNve4q9wgp0FoAXgh-:b-zb9603) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e87a958bb108155c912d41859c9532e9d294e735/migrations/generic/timetables/1663231564515_timetables_initial/up.sql#L61)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

E.g. let's assume we have a day type for Christmas Eve for which an actual day-of-week depends on the year. Is it meant that for such day type we populate an entry into this table for each seven day of week?
</blockquote></details>

well, with the current datamodel we should not have special day types like christmas eve... but if we wanna force this, then here's my suggestion:

My idea is kinda to follow the transmodel way (https://www.transmodel-cen.eu/model/index.htm?goto=1:6:3:294)

- So for regular day types, we have the day_type_active_on_day_of_week table to mark on what day it's active
- For yearly day types, we have the day_type_active_on_day_of_year table to mark that Christmas even is active on day ~358. For yearly day types, we do not define a day_type_active_on_day_of_week row.

This implicates that:
- When checking which day types are active on a given operating day, we'd need to go through both day_type_active_on_day_of_week and day_type_active_on_day_of_year tables, something like this:
```
  select *
    from day_type dt
      left join day_type_active_on_day_of_week dow on dow.day_type_id = dt.day_type_id
      left join day_type_active_on_day_of_year doy on doy.day_type_id = dt.day_type_id
      where (extract('dow', operating_day) = dow.day_of_week) OR (extract('doy', operating_day) = doy.day_of_year)   
```


<!-- Sent from Reviewable.io -->

2022-10-27 11:07 UTC, jarkkoka submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100#-:-NFO6uR60MVKaktqQu2J:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @jschummer and @pallost)

___
*[`migrations/generic/timetables/1663231564515_timetables_initial/up.sql` line 61 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100#-NFNlkw2B3b9zamCmb8H:-NFO66N28VPHHoF-RfPY:brqln3o) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e87a958bb108155c912d41859c9532e9d294e735/migrations/generic/timetables/1663231564515_timetables_initial/up.sql#L61)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

well, with the current datamodel we should not have special day types like christmas eve... but if we wanna force this, then here's my suggestion:

My idea is kinda to follow the transmodel way (https://www.transmodel-cen.eu/model/index.htm?goto=1:6:3:294)

- So for regular day types, we have the day_type_active_on_day_of_week table to mark on what day it's active
- For yearly day types, we have the day_type_active_on_day_of_year table to mark that Christmas even is active on day ~358. For yearly day types, we do not define a day_type_active_on_day_of_week row.

This implicates that:
- When checking which day types are active on a given operating day, we'd need to go through both day_type_active_on_day_of_week and day_type_active_on_day_of_year tables, something like this:
```
  select *
    from day_type dt
      left join day_type_active_on_day_of_week dow on dow.day_type_id = dt.day_type_id
      left join day_type_active_on_day_of_year doy on doy.day_type_id = dt.day_type_id
      where (extract('dow', operating_day) = dow.day_of_week) OR (extract('doy', operating_day) = doy.day_of_year)   
```
</blockquote></details>

Ok. Separation to day-of-week and day-of-year notions sounds like a good idea. :+1: 


<!-- Sent from Reviewable.io -->

2022-10-28 13:37 UTC, jarkkoka requested changes
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @jschummer and @pallost)

___
*[`migrations/generic/timetables/1666961618554_day_types/up.sql` line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100#-NFTn24n-3mA0hQXueeg:-NFTn24n-3mA0hQXueeh:bq6e6oy) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8417e637cba2d0bd0bd86b061adf3257967050ad/migrations/generic/timetables/1666961618554_day_types/up.sql#L2)):*
> ```TSQL
> CREATE TABLE service_calendar.day_type_active_on_day_of_week (
>   day_type_id UUID REFERENCES service_calendar.day_type (day_type_id) NOT NULL,
> ```

In this table data types should be changed to lowercase the same way as in the previous migration scripts.



_Code quote:_
```TSQL
UUID
```


<!-- Sent from Reviewable.io -->

2022-10-31 08:05 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @jschummer)

___
*[`migrations/generic/timetables/1666961618554_day_types/up.sql` line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100#-NFTn24n-3mA0hQXueeg:-NFh2mnZErRr_eUeIcdV:b-5a11zw) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8417e637cba2d0bd0bd86b061adf3257967050ad/migrations/generic/timetables/1666961618554_day_types/up.sql#L2)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In this table data types should be changed to lowercase the same way as in the previous migration scripts.
</blockquote></details>

ah, forgot about this one... fixed it!


<!-- Sent from Reviewable.io -->

2022-10-31 08:14 UTC, jarkkoka approved these changes
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer)



<!-- Sent from Reviewable.io -->

2022-10-31 09:52 UTC, merged