Fix insert_scheduled_stop_point_with_vehicle_mode function
HSLdevcom/jore4-hasura pull request #108
Opened 2022-11-02 11:25 UTC by jschummer

The function had to be redefined in the validity_time_as_date migration. The new definition inserted the scheduled stop point into the internal_service_pattern.scheduled_stop_point-table, skipping the service_pattern.scheduled_stop_point-view's trigger, which takes care of inserting a new scheduled_stop_point_invariant when needed. This commit re-defines the function the correct way.

The function was not previously tested, since it is not exposed in the gql-API. This commit also adds rudimentary unit-tests for the function.

2022-11-02 12:55 UTC, jarkkoka approved these changes
Noticed the cross-dependency between `service_pattern` and `internal_service_pattern` schemas. Not elegant but probably not very harmful either IMO.

Left some minor comments regarding the test code. It's good that you did add those tests in this same PR. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-:-NFsOOufBTpOYBcj-lHV:bocjrwa)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer)

___
*[`test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 72 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NFsJmUa7RFz3djQn2LG:-NFsJmUa7RFz3djQn2LH:b-y6kycm) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/91fdbf0b2c21315c84b8e58962e6eff6a5d70763/test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L72)):*
> ```XML
>         '${scheduledStopPoint.validity_start?.toISOString()}'::date,
>         '${scheduledStopPoint.validity_end?.toISOString()}'::date,
>         ${scheduledStopPoint.priority}::int,
> ```

tiny indent inconsistency



_Code quote:_
```XML
 $
```
___
*[`test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 93 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NFsKkx_ELIz3cu_nP3H:-NFsKkx_ELIz3cu_nP3I:btgtgj9) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/91fdbf0b2c21315c84b8e58962e6eff6a5d70763/test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L93)):*
> ```XML
>       expect.arrayContaining([
>         ...asDbGeometryObjectArray(scheduledStopPoints, ['measured_location']),
>         asDbGeometryObject(toBeInserted, ['measured_location']),
> ```

Hmmm...I wonder what is the primary point of this assertion. To check that geography value is correctly set in database if in doubt? Since the location field does not have unique constraint, this assertion does not guarantee that an existing row was not duplicated instead of adding a new row. That's why I'd primarily check that the new UUID is found in the table. However, this might be a matter of taste, how things should be asserted.



_Code quote:_
```XML
        ...asDbGeometryObjectArray(scheduledStopPoints, ['measured_location']),
        asDbGeometryObject(toBeInserted, ['measured_location']),
```


<!-- Sent from Reviewable.io -->

2022-11-03 06:26 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108)* status: all files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[`migrations/generic/default/1667313108899_fix_insert_scheduled_stop_point_with_vehicle_mode/up.sql` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NFw9WVB5loxLGiFG8Mp:-NFw9WVB5loxLGiFG8Mq:bjah7uv) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/91fdbf0b2c21315c84b8e58962e6eff6a5d70763/migrations/generic/default/1667313108899_fix_insert_scheduled_stop_point_with_vehicle_mode/up.sql#L25)):*
> ```TSQL
>   supported_vehicle_mode text
>   )
>   SET SCHEMA deleted;
> ```

I suggest we don't move stuff to the deleted schema anymore. It should be enough to just recreate the functions and views in the down migrations. Unfortunately references to these entities in the deleted schema stay, which is not the desired behaviour


<!-- Sent from Reviewable.io -->

2022-11-04 07:27 UTC, jschummer reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108)* status: all files reviewed, 3 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`migrations/generic/default/1667313108899_fix_insert_scheduled_stop_point_with_vehicle_mode/up.sql` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NFw9WVB5loxLGiFG8Mp:-NG0TJKD6K-lhvl5IN33:bplmhig) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/91fdbf0b2c21315c84b8e58962e6eff6a5d70763/migrations/generic/default/1667313108899_fix_insert_scheduled_stop_point_with_vehicle_mode/up.sql#L25)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I suggest we don't move stuff to the deleted schema anymore. It should be enough to just recreate the functions and views in the down migrations. Unfortunately references to these entities in the deleted schema stay, which is not the desired behaviour
</blockquote></details>

Yes, like discussed elsewhere, the whole migration will leave this PR anyway, because the same content is already included in your PR. So only the tests will be left.
___
*[`test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 72 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NFsJmUa7RFz3djQn2LG:-NG0TT1uCsmUz1JhMRaK:b1gy74n) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/91fdbf0b2c21315c84b8e58962e6eff6a5d70763/test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L72)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

tiny indent inconsistency
</blockquote></details>

Not really, because the other values are strings. This is the only value not encapsulated in single quotes, that's why it looks odd.
___
*[`test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 93 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NFsKkx_ELIz3cu_nP3H:-NG0TuFjAebkEChkJT_H:ba6abfw) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/91fdbf0b2c21315c84b8e58962e6eff6a5d70763/test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L93)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Hmmm...I wonder what is the primary point of this assertion. To check that geography value is correctly set in database if in doubt? Since the location field does not have unique constraint, this assertion does not guarantee that an existing row was not duplicated instead of adding a new row. That's why I'd primarily check that the new UUID is found in the table. However, this might be a matter of taste, how things should be asserted.
</blockquote></details>

The `asDbGeometryObject[Array]` function is only needed to convert the specified properties' (`measured_location`) values to the format returned by the SQL query.

So the whole check just verifies that the table contains all ssp previously present + the newly inserted one.


<!-- Sent from Reviewable.io -->

2022-11-07 07:42 UTC, pallost approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108)* status: 0 of 22 files reviewed, 4 unresolved discussions (waiting on @jarkkoka and @jschummer)

___
*[`test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 85 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NGG0k2n2vXCmKOHKZyv:-NGG0k2n2vXCmKOHKZyw:b-38peud) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/6ed3bf725e3ff7985594aed4b674feb31678fdb4/test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L85)):*
> ```XML
>     const response = await queryTable(
>       dbConnectionPool,
>       'service_pattern.scheduled_stop_point',
> ```

you should also check that the vehicle mode has been inserted
___
*[`test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 98 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NGG0qTIE3YNIean6p1W:-NGG0qTIE3YNIean6p1X:b-4gnckn) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/6ed3bf725e3ff7985594aed4b674feb31678fdb4/test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L98)):*
> ```XML
>   });
> 
>   it('should insert scheduled_stop_point_invariant row if invariant did not exist yet', async () => {
> ```

would like to see a test that if the insertion failed (e.g. invalid vehicle stop enum value) then neither the stop nor the vehicle mode got inserted


<!-- Sent from Reviewable.io -->

2022-11-07 10:29 UTC, jschummer reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108)* status: 0 of 22 files reviewed, 4 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 85 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NGG0k2n2vXCmKOHKZyv:-NGGcCOu9Zbm5aiuFg8r:b-euc7qx) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/6ed3bf725e3ff7985594aed4b674feb31678fdb4/test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L85)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should also check that the vehicle mode has been inserted
</blockquote></details>

Good point, added a test for that.
___
*[`test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 98 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/108#-NGG0qTIE3YNIean6p1W:-NGGcbx73qINnboJ0XDn:b7btdpz) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/6ed3bf725e3ff7985594aed4b674feb31678fdb4/test/hasura/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L98)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

would like to see a test that if the insertion failed (e.g. invalid vehicle stop enum value) then neither the stop nor the vehicle mode got inserted
</blockquote></details>

Not sure this belongs here, because the function itself does not implement this functionality. (Of course it works the way you describe if you call the function from a transaction context, but it's not the tested function that is responsible for this mechanism working or not.)


<!-- Sent from Reviewable.io -->

2022-11-07 10:29 UTC, merged