Create framework for running Hasura repeatable migrations
HSLdevcom/jore4-hasura pull request #111
Opened 2022-11-11 08:01 UTC by pallost

We remove the migration records from Hasura's hdb_catalog.hdb_version table for some dedicated migrations. Thus when restarting the hasura container, these migrations will be rerun in the order of their timestamps

2022-11-11 10:18 UTC, jarkkoka reviewed
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[`migrations/generic/default/2000000000000_after_migrate/up.sql` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGaAZA0-J5pSPZGe6K4:-NGaAZA19XEt2vziKHdb:bmyq7ud) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/b1ba8a92eb413e4d75ce2654a7799e80c5380c7a/migrations/generic/default/2000000000000_after_migrate/up.sql#L1)):*
> ```TSQL
> SELECT 'network database; after migrate hook; up migration';
> ```

Is this a sort of placeholder for future function definitions that will be replaced whenever they are changed?



_Code quote:_
```TSQL
SELECT 'network database; after migrate hook; up migration';
```


<!-- Sent from Reviewable.io -->

2022-11-11 13:03 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`migrations/generic/default/2000000000000_after_migrate/up.sql` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGaAZA0-J5pSPZGe6K4:-NGamHpx6xjwGio9fgll:b-ss56ia) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/b1ba8a92eb413e4d75ce2654a7799e80c5380c7a/migrations/generic/default/2000000000000_after_migrate/up.sql#L1)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Is this a sort of placeholder for future function definitions that will be replaced whenever they are changed?
</blockquote></details>

yes, exactly :thumbsup: 


<!-- Sent from Reviewable.io -->

2022-11-11 13:26 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`migrations/generic/default/2000000000000_after_migrate/up.sql` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGaAZA0-J5pSPZGe6K4:-NGapfYH3gNO5HUYBgFS:bkhcl55) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/b1ba8a92eb413e4d75ce2654a7799e80c5380c7a/migrations/generic/default/2000000000000_after_migrate/up.sql#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yes, exactly :thumbsup: 
</blockquote></details>

Ok, nice. Then I would prepend the SQL clause with the following comment line (possibly divided into several lines) to make this point clear:

```sql
-- This is a repeatable migration script used to replace function definitions with new versions whenever changes occur. 
```

The same applies to other databases.
___
*[`migrations/generic/timetables/1000000000000_before_migrate/down.sql` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGaqgrq1JIblLMF0OYP:-NGaqgrr35hSRXLDikoy:b-ubw5o5) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/b1ba8a92eb413e4d75ce2654a7799e80c5380c7a/migrations/generic/timetables/1000000000000_before_migrate/down.sql#L1)):*
> ```TSQL
> SELECT 'timetables database; before migrate hook; down migration';
> ```

I would prepend the SQL clause with the following comment line (possibly divided into several lines):

```sql
-- This is a repeatable migration script used to replace function definitions with old versions whenever changes have occurred. 
```

The same applies to other databases.



_Code quote:_
```TSQL
SELECT 'timetables database; before migrate hook; down migration';
```


<!-- Sent from Reviewable.io -->

2022-11-14 12:24 UTC, jarkkoka approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Some minor remarks

> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-:-NGq4sbd6Jq0OukXmrKP:b-eoh3o5)* status: all files reviewed, 6 unresolved discussions (waiting on @pallost)

___
*[`scripts/repeatable-migrations.sh` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGq3F1V-rkCqY5Nfi5n:-NGq3F1V-rkCqY5Nfi5o:blevjtg) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/9b4488a105b9b67746fa4798f4c39df89c603b9a/scripts/repeatable-migrations.sh#L7)):*
> ```Shell
> # This script is used to enable repeatable migrations in Hasura. It does the following:
> # 1. checks if Hasura migrations have ever been run. If not, there's no need for any tweaks
> # 2. finds all the migrations that are having the "<timestamp>_R_<migration name>" pattern
> ```

"match" sounds more fluent English IMO 



_Code quote:_
```Shell
are having
```
___
*[`scripts/repeatable-migrations.sh` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGq3Wem7WxHoYS5hGFh:-NGq3Wem7WxHoYS5hGFi:b-hdf41s) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/9b4488a105b9b67746fa4798f4c39df89c603b9a/scripts/repeatable-migrations.sh#L10)):*
> ```Shell
> # 3. removes these timestamp entries from Hasura's hdb_catalog.hdb_version table
> # When hasura is started, it thinks that these migrations have not been run yet so it runs them again
> # Note: we expect repeatable migrations to be idempotent
> ```

require



_Code quote:_
```Shell
expect
```
___
*[`scripts/repeatable-migrations.sh` line 37 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGq48621VsrUJCUApTG:-NGq48621VsrUJCUApTH:b-dtogn5) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/9b4488a105b9b67746fa4798f4c39df89c603b9a/scripts/repeatable-migrations.sh#L37)):*
> ```Shell
> for DB in "${DATABASES[@]}"
> do
> 	echo "Looking for repeatable migrations for database: $DB"
> ```

Looks like there is a different indent on this line. Is there a tab character?
___
*[`scripts/repeatable-migrations.sh` line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGq4Z4-0xX4G2TuTW78:-NGq4Z4-0xX4G2TuTW79:b-fbvqfg) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/9b4488a105b9b67746fa4798f4c39df89c603b9a/scripts/repeatable-migrations.sh#L40)):*
> ```Shell
> 
>   # use regex to find all matching migration names and grep to extract the timestamp part, then put it into an array
>   TIMESTAMPS=($(find "${HASURA_GRAPHQL_MIGRATIONS_DIR}" -type d -regex ".*/${DB}/[0-9]*_R_.*" | grep -oE "[0-9]{13}"))
> ```

wow, impressively expressive



_Code quote:_
```Shell
TIMESTAMPS=($(find "${HASURA_GRAPHQL_MIGRATIONS_DIR}" -type d -regex ".*/${DB}/[0-9]*_R_.*" | grep -oE "[0-9]{13}"))
```


<!-- Sent from Reviewable.io -->

2022-11-15 07:59 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka)

___
*[`scripts/repeatable-migrations.sh` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGq3F1V-rkCqY5Nfi5n:-NGuHquh-nfmPm9D2NOm:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/9b4488a105b9b67746fa4798f4c39df89c603b9a/scripts/repeatable-migrations.sh#L7)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"match" sounds more fluent English IMO 
</blockquote></details>

Done.
___
*[`scripts/repeatable-migrations.sh` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGq3Wem7WxHoYS5hGFh:-NGuHlqF9w0UhtsTITYs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/9b4488a105b9b67746fa4798f4c39df89c603b9a/scripts/repeatable-migrations.sh#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

require
</blockquote></details>

Done.
___
*[`scripts/repeatable-migrations.sh` line 37 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGq48621VsrUJCUApTG:-NGuHagA70B2DdeTAPLq:bxfgq7) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/9b4488a105b9b67746fa4798f4c39df89c603b9a/scripts/repeatable-migrations.sh#L37)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Looks like there is a different indent on this line. Is there a tab character?
</blockquote></details>

weird, I don't know why my IDE made this into a tab character. Fixed it.
___
*[`scripts/repeatable-migrations.sh` line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGq4Z4-0xX4G2TuTW78:-NGuHfo01Lde5eJSU6S6:b-qa8hh8) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/9b4488a105b9b67746fa4798f4c39df89c603b9a/scripts/repeatable-migrations.sh#L40)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

wow, impressively expressive
</blockquote></details>

regex is awesome :)
___
*[`migrations/generic/default/2000000000000_after_migrate/up.sql` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGaAZA0-J5pSPZGe6K4:-NGuI3iT7jegUaCK6UOj:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/b1ba8a92eb413e4d75ce2654a7799e80c5380c7a/migrations/generic/default/2000000000000_after_migrate/up.sql#L1)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, nice. Then I would prepend the SQL clause with the following comment line (possibly divided into several lines) to make this point clear:

```sql
-- This is a repeatable migration script used to replace function definitions with new versions whenever changes occur. 
```

The same applies to other databases.
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/1000000000000_before_migrate/down.sql` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/111#-NGaqgrq1JIblLMF0OYP:-NGuHsAY2tFjkghoqAJ5:b-m056kw) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/b1ba8a92eb413e4d75ce2654a7799e80c5380c7a/migrations/generic/timetables/1000000000000_before_migrate/down.sql#L1)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would prepend the SQL clause with the following comment line (possibly divided into several lines):

```sql
-- This is a repeatable migration script used to replace function definitions with old versions whenever changes have occurred. 
```

The same applies to other databases.
</blockquote></details>

Technically only the `up` migrations are repeatable, so I only added the comment there.


<!-- Sent from Reviewable.io -->

2022-11-15 08:18 UTC, merged