Add hastus fields to timetables data model
HSLdevcom/jore4-hasura pull request #148
Opened 2023-02-15 11:09 UTC by tk-vincit

Resolves HSLdevcom/jore4#1129

2023-02-15 13:27 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @tk-vincit)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 3 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKELO38ak_mA5y9zGN:-NOKELO40pH5d_2PhBBz:b-gamu4w) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L3)):*
> ```TSQL
> ALTER TABLE vehicle_service.block
>   ADD COLUMN start_timing_place text,
>   ADD COLUMN end_timing_place text,
> ```

Are these references to the `timing_pattern.timing_place` table in routes DB? Quite sounds like they might be. If so, should maybe be UUID instead, and clarify in comment (similar field: `journey_pattern.journey_pattern_ref.journey_pattern_id`).

Also, these are named differently than in the related issue. I assume this was discussed with Teemu?
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKDt3M36_CagLhju7o:-NOKDt3M36_CagLhju7p:b-hu3x86) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L5)):*
> ```TSQL
>   ADD COLUMN end_timing_place text,
>   ADD COLUMN preparing_duration smallint,
>   ADD COLUMN finishing_duration smallint,
> ```

Is smallint the best type for these duration fields? What kind of values do these represent? Should we maybe use eg. `interval` instead?
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKB2AD8iL__9vN1_G0:-NOKB2AD8iL__9vN1_G1:b-l4bdfe) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L6)):*
> ```TSQL
>   ADD COLUMN preparing_duration smallint,
>   ADD COLUMN finishing_duration smallint,
>   ADD COLUMN vehicle_type smallint;
> ```

Any more info on this? Sounds like a magic number.
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKDLdFDgypO0cp82h5:-NOKDLdG4kggtMGkH1es:b5l3zzv) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L18)):*
> ```TSQL
>   ADD COLUMN journey_name text;
> 
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.number IS 'Journey name.';
> ```

Comment on incorrect column here?
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 8 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKCvDG1rvZoybeMO4Q:-NOKCvDH2qVOEOfeBpcS:bhl7s6z) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L8)):*
> ```TSQL
>   ADD COLUMN is_vehicle_type_mandatory boolean,
>   ADD COLUMN backup_journey boolean,
>   ADD COLUMN extra_journey boolean;
> ```

Inconsistency: some boolean fields are prefixed with `is_`, some are not. Is this fine?
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKBFlM7QgMYCwIrscF:-NOKBFlM7QgMYCwIrscG:b-va5bac) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L10)):*
> ```TSQL
>   ADD COLUMN extra_journey boolean;
> 
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.journey_type IS 'STANDARD | PULL_OUT | PULL_IN | TRANSFER';
> ```

This could probably be an enum instead? See eg. `hsl_route.transport_target` and https://hasura.io/docs/latest/schema/postgres/enums/#pg-create-enum-table
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKCF_z6TGrlraao_eL:-NOKCF_z6TGrlraao_eM:bczfrav) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L13)):*
> ```TSQL
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.displayed_name IS 'Displayed name of the journey.';
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.lay_start_time_minutes IS 'Terminal time.';
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.lay_end_time_minutes IS 'Recovery time';
> ```

I don't quite grasp what the comments on these two time fields mean.

The field names sound like they would be value of minutes during the hour, as in 0-59. If this is the case, these should be limited to 0-59 with a constraint? Or is it something else?

Anyway, maybe needs some clarification.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKDXJE6bo5gOTZLxrx:-NOKDXJE6bo5gOTZLxry:br69lxf) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L14)):*
> ```TSQL
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.lay_start_time_minutes IS 'Terminal time.';
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.lay_end_time_minutes IS 'Recovery time';
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.is_vehicle_type_mandatory IS 'Is is required to use the same vehicle type as required in vehicle service.';
> ```

Typo, `Is is`


<!-- Sent from Reviewable.io -->

2023-02-15 13:47 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 13 unresolved discussions (waiting on @culka, @Leitsi, and @tk-vincit)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 3 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKELO38ak_mA5y9zGN:-NOKGef0BrzgIzRusbzY:bq8kmdw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L3)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Are these references to the `timing_pattern.timing_place` table in routes DB? Quite sounds like they might be. If so, should maybe be UUID instead, and clarify in comment (similar field: `journey_pattern.journey_pattern_ref.journey_pattern_id`).

Also, these are named differently than in the related issue. I assume this was discussed with Teemu?
</blockquote></details>

agreed. Better reference these by UUID. Also, these fields most likely are going to be generated based on the stops in journey pattern table's content
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKDt3M36_CagLhju7o:-NOKGtKZA-Ym80DcYSkM:b2x68ko) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L5)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Is smallint the best type for these duration fields? What kind of values do these represent? Should we maybe use eg. `interval` instead?
</blockquote></details>

yes, we use interval type for times. They can be summed easier
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKB2AD8iL__9vN1_G0:-NOKH5aRAIuJlIezwIH4:b-loxd82) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L6)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Any more info on this? Sounds like a magic number.
</blockquote></details>

you should rather store the existing vehicle types as some kind of an enum in a separate table. And then reference it from here. I wonder, is there any need for these legacy numeric codes for us or the Hastus importer could just do the mapping. Maybe @culka knows more about that
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKDLdFDgypO0cp82h5:-NOKI7bw3MvPh0wlUY-v:b-ypdid2) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L18)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Comment on incorrect column here?
</blockquote></details>

is this generated somehow? Also, why is the vehicle service name localized and this isn't?
I could even imagine calling this field as 'label' if it's used for some kind of identification. 'name' is something that we've used for human-assigned values
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 12 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKI_qj9jRCRN9PUypY:-NOKI_qj9jRCRN9PUypZ:b4706k1) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L12)):*
> ```TSQL
> COMMENT ON COLUMN vehicle_service.block.preparing_duration IS 'Preparation time before start.';
> COMMENT ON COLUMN vehicle_service.block.finishing_duration IS 'Finishing time after end.';
> COMMENT ON COLUMN vehicle_service.block.vehicle_type IS 'Vehicle type.';
> ```

do blocks also need a 'name' or a 'label' as the other entities below?
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 24 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKIF1i75lwqKijF1D6:-NOKIF1i75lwqKijF1D7:b-x7gtfc) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L24)):*
> ```TSQL
>   ADD COLUMN name_i18n jsonb;
> 
> COMMENT ON COLUMN vehicle_service.vehicle_service.name_i18n IS 'Name for vehicle service.';
> ```

is this generated somehow?
I could even imagine calling this field as 'label' if it's used for some kind of identification. 'name' is something that we've used for human-assigned values
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKBFlM7QgMYCwIrscF:-NOKJ81U7KDL7AUGNRUb:brnhm0w) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L10)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This could probably be an enum instead? See eg. `hsl_route.transport_target` and https://hasura.io/docs/latest/schema/postgres/enums/#pg-create-enum-table
</blockquote></details>

where do these values come from? Are they valuable in some use? Also, Transmodel defines e.g. "Dry run" and "Service Journey" for vehicle journeys, should we rather use those?
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKIzqR81wy17MH3aav:-NOKIzqR81wy17MH3aaw:b24fzah) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L4)):*
> ```TSQL
>   ADD COLUMN journey_type text,
>   ADD COLUMN displayed_name text,
>   ADD COLUMN lay_start_time_minutes smallint,
> ```

time values should use 'interval' type
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKIqeBB_E6R3VVIL58:-NOKIqeBB_E6R3VVIL59:b2xs0fc) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L11)):*
> ```TSQL
> 
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.journey_type IS 'STANDARD | PULL_OUT | PULL_IN | TRANSFER';
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.displayed_name IS 'Displayed name of the journey.';
> ```

is the 'displayed_name' field generated? Should it be localized? Or would 'label' be a better name for the column?
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 22 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKJp2_BlH9KX4iwpSb:-NOKJp2_BlH9KX4iwpSc:b5a2qi0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L22)):*
> ```TSQL
>   ADD COLUMN booking_label text,
>   RENAME COLUMN name_i18n TO booking_description_i18n,
>   ADD COLUMN timetable_name text;
> ```

should the timetable_name field also be localized as the description above? Also, I think this is rather called "booking_name". "timetable_name" is too generic and doesn't tell about its actual source/use


<!-- Sent from Reviewable.io -->

2023-02-17 11:27 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 12 unresolved discussions (waiting on @culka, @Leitsi, and @pallost)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKDt3M36_CagLhju7o:-NOTy4GY9CmbQn-zxPek:by4tuk0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yes, we use interval type for times. They can be summed easier
</blockquote></details>

Refactored to interval
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKDLdFDgypO0cp82h5:-NONvqPC5um8JDoiwCEZ:bwomkbm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

is this generated somehow? Also, why is the vehicle service name localized and this isn't?
I could even imagine calling this field as 'label' if it's used for some kind of identification. 'name' is something that we've used for human-assigned values
</blockquote></details>

Why this would be on wrong column?
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 12 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKI_qj9jRCRN9PUypY:-NOU-VRF-YtqPzBdCVDD:b-egjl13) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

do blocks also need a 'name' or a 'label' as the other entities below?
</blockquote></details>

:nope: says @culka 
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 24 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKIF1i75lwqKijF1D6:-NOU1JIU2gKgvk-_OZey:bam41uj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L24)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

is this generated somehow?
I could even imagine calling this field as 'label' if it's used for some kind of identification. 'name' is something that we've used for human-assigned values
</blockquote></details>

Is there something wrong with the comment?

User can assign this field in hastus.  Hastus only supports finnish language, but we can fallback to that in ui, and if we get other users they can add the translations as they want.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 8 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKCvDG1rvZoybeMO4Q:-NOU1ypO11vxmwCCoy2Q:bv8fnv3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L8)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Inconsistency: some boolean fields are prefixed with `is_`, some are not. Is this fine?
</blockquote></details>

Good point, added prefixes as they seem to be our convention.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKBFlM7QgMYCwIrscF:-NOU2q6D5VJiuyFsgaJX:b-xv30el) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

where do these values come from? Are they valuable in some use? Also, Transmodel defines e.g. "Dry run" and "Service Journey" for vehicle journeys, should we rather use those?
</blockquote></details>

@culka created ticket about this.
https://github.com/HSLdevcom/jore4/issues/1176
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKCF_z6TGrlraao_eL:-NOU4f4o-efiGyBlz57r:b-uhjrwi) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L13)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I don't quite grasp what the comments on these two time fields mean.

The field names sound like they would be value of minutes during the hour, as in 0-59. If this is the case, these should be limited to 0-59 with a constraint? Or is it something else?

Anyway, maybe needs some clarification.
</blockquote></details>

Do you have suggestions how to improve these? Meaning of these is not too clear for us either. :/ These come from hastus and are passed through jore4.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKIzqR81wy17MH3aav:-NONuDes5tVxYbyDLNHa:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

time values should use 'interval' type
</blockquote></details>

Done.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKIqeBB_E6R3VVIL58:-NOU4IRF4OHmCGF49LZz:bk5wp1s) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

is the 'displayed_name' field generated? Should it be localized? Or would 'label' be a better name for the column?
</blockquote></details>

This comes from hastus and in single language.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 22 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKJp2_BlH9KX4iwpSb:-NOU5YWH7VXCJim-E4NY:b-diqwtq) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should the timetable_name field also be localized as the description above? Also, I think this is rather called "booking_name". "timetable_name" is too generic and doesn't tell about its actual source/use
</blockquote></details>

@culka suggested 'label'


<!-- Sent from Reviewable.io -->

2023-02-17 12:41 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @culka, @pallost, and @tk-vincit)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKDLdFDgypO0cp82h5:-NOULK-F4ypZH9EFmGkV:bar20wn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L18)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why this would be on wrong column?
</blockquote></details>

Used to be `number IS 'Journey name.';` when I added the comment, seems to be resolved.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKCF_z6TGrlraao_eL:-NOULxk4CRWPyVxLJAIM:bcptepm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do you have suggestions how to improve these? Meaning of these is not too clear for us either. :/ These come from hastus and are passed through jore4.
</blockquote></details>

Fair enough. Maybe clarify & add constraints when we have more info.

Though, I still don't get the terminology here, mainly the terminal/recovery time comments. :shrug: 


<!-- Sent from Reviewable.io -->

2023-02-20 07:29 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @culka, @Leitsi, and @tk-vincit)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 24 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKIF1i75lwqKijF1D6:-NOhffQy3MPsT86bkMIK:bx1zffh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L24)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is there something wrong with the comment?

User can assign this field in hastus.  Hastus only supports finnish language, but we can fallback to that in ui, and if we get other users they can add the translations as they want.
</blockquote></details>

If this can be assigned in Hastus, then this is fine :+1: Good that you used an i18n field to make it extensible in the future. In case...
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKBFlM7QgMYCwIrscF:-NOhg7j_4PvB8E7m2ZJV:b-btgliv) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

@culka created ticket about this.
https://github.com/HSLdevcom/jore4/issues/1176
</blockquote></details>

The ticket was about vehicle types. This is a journey_type. My question still stands :)
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 22 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKJp2_BlH9KX4iwpSb:-NOhibET7eiJjsGZbG3k:bq0ncok) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/d85e76672b81bf65456eca5b9de8153c033ba6f2/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L22)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

@culka suggested 'label'
</blockquote></details>

sounds good


<!-- Sent from Reviewable.io -->

2023-02-20 07:52 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @culka, @Leitsi, and @tk-vincit)

___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 22 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOhnnRB-5Yh9ZnPQtC5:-NOhnnRB-5Yh9ZnPQtC6:bifherw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/658e1b40d8ddf5317764bd87e827f68508f44fb6/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L22)):*
> ```TSQL
>   ADD COLUMN booking_label text,
>   RENAME COLUMN name_i18n TO booking_description_i18n,
>   ADD COLUMN label text;
> ```

if this is label, let's move this to the generic data model and make it NOT NULLABLE


<!-- Sent from Reviewable.io -->

2023-02-20 07:55 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @culka, @Leitsi, and @tk-vincit)

___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOhoT4U10Su7rHIDfG5:-NOhoT4U10Su7rHIDfG6:b8w6eb5) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/658e1b40d8ddf5317764bd87e827f68508f44fb6/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L2)):*
> ```TSQL
> ALTER TABLE vehicle_journey.vehicle_journey
>   ADD COLUMN journey_type text,
> ```

I think most of these should be NOT NULLABLE
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOhoDIhB3cB4kZreLo9:-NOhoDIhB3cB4kZreLoA:blj4uwp) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/658e1b40d8ddf5317764bd87e827f68508f44fb6/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L10)):*
> ```TSQL
>   ADD COLUMN is_extra_journey boolean;
> 
> COMMENT ON COLUMN vehicle_journey.vehicle_journey.journey_type IS 'STANDARD | PULL_OUT | PULL_IN | TRANSFER';
> ```

journey_type is a transmodel concept, it specifies the type of a DRY RUN that is used. Let's move this to the generic data model and make it NOT NULLABLE DEFAULT STANDARD


<!-- Sent from Reviewable.io -->

2023-02-20 08:18 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @culka, @Leitsi, and @tk-vincit)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKB2AD8iL__9vN1_G0:-NOhtAwX333xZd1UXYJ6:b-908atz) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should rather store the existing vehicle types as some kind of an enum in a separate table. And then reference it from here. I wonder, is there any need for these legacy numeric codes for us or the Hastus importer could just do the mapping. Maybe @culka knows more about that
</blockquote></details>

Maybe let's actually use the more modern TRANSPORT TYPE entity for this: https://www.transmodel-cen.eu/model/EARoot/EA10/EA3/EA4/EA3580.htm

Let's create a table to the generic data model with the name "transport type" that contains at least a name and and uuid field. Let's extend it with a "hsl_transport_type" column in the hsl data model. Let's reference that table from vehicle_service.block through uuid


<!-- Sent from Reviewable.io -->

2023-02-20 08:30 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @culka, @Leitsi, and @tk-vincit)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOhwMrZBTtcGO3hVpcl:-NOhwMr_AVgKZJikwlkb:bp6ii1v) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/658e1b40d8ddf5317764bd87e827f68508f44fb6/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L2)):*
> ```TSQL
> ALTER TABLE vehicle_service.block
>   ADD COLUMN preparing_duration interval,
> ```

should this be actually preparing_time and finishing_time?


<!-- Sent from Reviewable.io -->

2023-02-20 08:40 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @culka, @Leitsi, and @tk-vincit)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKB2AD8iL__9vN1_G0:-NOhyVhs9hWapnjcNdKq:bw0dw0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Maybe let's actually use the more modern TRANSPORT TYPE entity for this: https://www.transmodel-cen.eu/model/EARoot/EA10/EA3/EA4/EA3580.htm

Let's create a table to the generic data model with the name "transport type" that contains at least a name and and uuid field. Let's extend it with a "hsl_transport_type" column in the hsl data model. Let's reference that table from vehicle_service.block through uuid
</blockquote></details>

actually, after some reading it's clear that we need VEHICLE TYPE here. TRANSPORT TYPE is a common concept that includes both public transportation vehicles (VEHICLE TYPE) and private transportation vehicles (SIMPLE VEHICLE TYPE). We don't need the private transportation concept here


<!-- Sent from Reviewable.io -->

2023-02-22 07:59 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @culka, @Leitsi, and @pallost)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 3 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKELO38ak_mA5y9zGN:-NOny4431hnSNe7RZh2C:b-f386eh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

agreed. Better reference these by UUID. Also, these fields most likely are going to be generated based on the stops in journey pattern table's content
</blockquote></details>

Removed these fields as we decided that these are not needed.
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKB2AD8iL__9vN1_G0:-NOo0sPS8H5r7vUhFboU:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually, after some reading it's clear that we need VEHICLE TYPE here. TRANSPORT TYPE is a common concept that includes both public transportation vehicles (VEHICLE TYPE) and private transportation vehicles (SIMPLE VEHICLE TYPE). We don't need the private transportation concept here
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOhwMrZBTtcGO3hVpcl:-NOnkJdcEjwDSce4AGJO:b-lx5p5w) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/658e1b40d8ddf5317764bd87e827f68508f44fb6/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should this be actually preparing_time and finishing_time?
</blockquote></details>

Refactored to _duration postfixes to _time
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKBFlM7QgMYCwIrscF:-NOo3ctgC42zzcBNn4E2:bfdcwd2) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

The ticket was about vehicle types. This is a journey_type. My question still stands :)
</blockquote></details>

Created enum table for these.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOKCF_z6TGrlraao_eL:-NOngH5s8_wxN737JbUR:b-z8ulbl) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/afc6c1a46f5ff8c27fd36e1c1795adcd51f06436/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L13)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Fair enough. Maybe clarify & add constraints when we have more info.

Though, I still don't get the terminology here, mainly the terminal/recovery time comments. :shrug: 
</blockquote></details>

There was a slack discussion regarding these and tried to update comments accordingly: https://vincit.slack.com/archives/CNG9QULAH/p1676885003712519
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOhoT4U10Su7rHIDfG5:-NOo1A1G2ty6ZLGkIOSz:bquw6e9) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/658e1b40d8ddf5317764bd87e827f68508f44fb6/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think most of these should be NOT NULLABLE
</blockquote></details>

First three come from hastus and thus might be null.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOhoDIhB3cB4kZreLo9:-NOngwRE7mLZAkCVdzRo:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/658e1b40d8ddf5317764bd87e827f68508f44fb6/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

journey_type is a transmodel concept, it specifies the type of a DRY RUN that is used. Let's move this to the generic data model and make it NOT NULLABLE DEFAULT STANDARD
</blockquote></details>

Done.
___
*[`migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql` line 22 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOhnnRB-5Yh9ZnPQtC5:-NOnb9NaDSVQPpR3zQf0:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/658e1b40d8ddf5317764bd87e827f68508f44fb6/migrations/hsl/timetables/1676027954829_add_hastus_fields/up.sql#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

if this is label, let's move this to the generic data model and make it NOT NULLABLE
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-23 10:15 UTC, Leitsi requested changes

2023-02-23 10:15 UTC, Leitsi commented on migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql
> +  ADD COLUMN vehicle_type uuid;
Should this be `vehicle_type_id`?

2023-02-23 10:15 UTC, Leitsi commented on migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql
> +COMMENT ON COLUMN vehicle_service.block.vehicle_type IS 'Reference to resuable_components.vehicle_type.';
Typo, resuable -> reusable

2023-02-23 10:28 UTC, pallost requested changes

2023-02-23 10:28 UTC, pallost commented on migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql
> +COMMENT ON COLUMN vehicle_journey.vehicle_journey.turnaround_time IS 'Turnaround time. Means the time it takes to move vehicle to the starting stop and pick up the passengers.';
The Transmodel definition might be a bit better: Turnaround time is the time taken by a vehicle to proceed from the end of a ROUTE to the start of another

2023-02-23 10:28 UTC, pallost commented on migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql
> +COMMENT ON COLUMN vehicle_journey.vehicle_journey.layover_time IS 'Layover time. 95% of the journeys should arrive to the terminal within journey time + recovery time so that they would be ready to s
The Transmodel definition might be a bit better: LAYOVER TIMEs describe a certain time allowance that may be given at the end of each VEHICLE JOURNEY, before starting the next one, to compensate delays or for other purposes (e.g. rest time for the driver). This “layover time” can be regarded as a buffer time, which may or may not be actually consumed in real time operation.

2023-02-23 10:28 UTC, pallost commented on migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql
> +CREATE TABLE reusable_components.vehicle_type (
In Transmodel, VEHICLE TYPE belongs to the Vehicle Type model. I'd rather name the schema accordingly: `vehicle_type.vehicle_type`

2023-02-23 10:28 UTC, pallost commented on migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql
> +COMMENT ON COLUMN vehicle_journey.vehicle_journey.displayed_label IS 'Displayed name of the journey.';
I think this should rather be called "displayed_name". For us, "label" are kind of identifiers, so "display_label" sounds a bit weird

2023-02-23 10:28 UTC, pallost commented on migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql
> +  ADD COLUMN label text;
the label should be NOT NULLABLE as it's kind of an identifier

2023-02-23 10:28 UTC, pallost commented on migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql
> +ALTER TABLE ONLY vehicle_service.block
let's also create an index for vehicle_type column. By default, foreign key fields are unfortunately not indexes in postgresql

2023-02-23 10:28 UTC, pallost commented on migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql
> +  ALTER COLUMN booking_label SET NOT NULL;
nice solution!

2023-02-23 10:28 UTC, pallost commented on migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql
> +  ADD COLUMN hsl_id smallint;
I wonder, should this be NOT NULLABLE

2023-02-23 11:16 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 7 files reviewed, 18 unresolved discussions (waiting on @culka, @Leitsi, and @pallost)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 20 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOJl1IvkwFEEISyxV7Q-r6-20:-NOxwa7G-_xk-sJUpUV9:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

The Transmodel definition might be a bit better: Turnaround time is the time taken by a vehicle to proceed from the end of a ROUTE to the start of another
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 21 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOJl1IvkwFEEISyxV7Q-r6-21:-NOxwhnz-ar4Cvhnne0j:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

The Transmodel definition might be a bit better: LAYOVER TIMEs describe a certain time allowance that may be given at the end of each VEHICLE JOURNEY, before starting the next one, to compensate delays or for other purposes (e.g. rest time for the driver). This “layover time” can be regarded as a buffer time, which may or may not be actually consumed in real time operation.
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 26 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOJl1IvkwFEEISyxV7Q-r6-26:-NOxxIbA9FLM52H9Eq-0:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

In Transmodel, VEHICLE TYPE belongs to the Vehicle Type model. I'd rather name the schema accordingly: `vehicle_type.vehicle_type`
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 38 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOJl1IvkwFEEISyxV7Q-r6-38:-NOxylOn43cTHlRbxFXv:b1zy367) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L38)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Should this be `vehicle_type_id`?
</blockquote></details>

Maybe. Changed this.
___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 47 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOJl1IvkwFEEISyxV7Q-r6-47:-NOxxnwT7H44aLGH_dcE:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L47)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the label should be NOT NULLABLE as it's kind of an identifier
</blockquote></details>

Done.
___
*[`migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql` line 7 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOssGcsIVZpAO9-IBtd-r6-7:-NOxy5Hd9YLILRmQSIcs:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think this should rather be called "displayed_name". For us, "label" are kind of identifiers, so "display_label" sounds a bit weird
</blockquote></details>

Done.
___
*[`migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql` line 19 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOssGcsIVZpAO9-IBtd-r6-19:-NOxyAKo5pG7GqYLmygN:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql#L19)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

nice solution!
</blockquote></details>

Done.
___
*[`migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOssGcsIVZpAO9-IBtd-r6-24:-NOxyGUDCZ2BTVqa-kE6:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/hsl/timetables/1676027954830_add_hastus_fields/up.sql#L24)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I wonder, should this be NOT NULLABLE
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-23 11:27 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148)* status: 0 of 7 files reviewed, 18 unresolved discussions (waiting on @culka, @Leitsi, and @pallost)

___
*[`migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql` line 39 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/148#-NOJl1IvkwFEEISyxV7Q-r6-39:-NOy-9zM10SygMfOzmwm:b-x9ba83) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/843250cc4b3811906eea2f75155d88124fcd2f4c/migrations/generic/timetables/1676027954829_add_hastus_fields/up.sql#L39)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's also create an index for vehicle_type column. By default, foreign key fields are unfortunately not indexes in postgresql
</blockquote></details>

Like this?


<!-- Sent from Reviewable.io -->

2023-02-23 12:26 UTC, pallost approved these changes

2023-02-23 17:26 UTC, merged