Add validation for vehicle journey passing time and stop point sequences
HSLdevcom/jore4-hasura pull request #149
Opened 2023-02-22 08:26 UTC by Leitsi

Resolves https://github.com/HSLdevcom/jore4/issues/1015

2023-02-22 12:08 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149)* status: 0 of 19 files reviewed, 17 unresolved discussions (waiting on @Leitsi)

___
*[`README.md` line 120 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOst75V2Ngp7EUnX3hy:-NOst75W76DJOQlfStc4:bcgo7aq) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/README.md#L120)):*
> ```Markdown
> 
> Data validation relies largely on triggers, which can get heavy to run with large amounts of data.
> EXPLAIN ANALYZE can't normally be used for optimizing these because query plans retrieved with it do not include triggered functions.
> ```

also remember that queries are run a different way in case there's actually lots of data in the database. The optimizer might choose to run the queries using different indexes compared to how it would run it in case of little amount of data. So trying to optimize your queries now, without any much seed data might be misleading
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 19 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsw1o3BkjnSFUVSVaX:-NOsw1o3BkjnSFUVSVaY:b-hxxb07) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L19)):*
> ```TSQL
>     SELECT
>       tpt.*,
>       ssp.*,
> ```

I didn't notice that you'd use the `ssp.*` columns below. I think it could be removed from here
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 39 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsv6kc6CoLeslAv1cG:-NOsv6kc6CoLeslAv1cH:b-e2leqp) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L39)):*
> ```TSQL
>     SELECT
>       combo.*,
>       combo.passing_time > previous_combo.passing_time AS is_after_previous
> ```

I think we could also allow `>=` relation here (so that the same passing time is marked for multiple stops)
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 107 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsxB7NDn_lJu5ejjvy:-NOsxB7NDn_lJu5ejjvz:b-jyo6gu) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L107)):*
> ```TSQL
>     RETURN TRUE;
>   ELSE
>     SET LOCAL passing_times_vars.passing_times_sequence_already_validated = TRUE;
> ```

I needed to look this up. Could you please put a comment here that this "already_validated" variable is scoped only for the current transaction
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 130 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsxeTz-yBGVvxU81zX:-NOsxeTz-yBGVvxU81zY:b3x6smz) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L130)):*
> ```TSQL
>   RETURN NULL;
> END;
> $$;
> ```

could you create a comment for this function? Do I understand it correctly that it just adds the modified table's vehicle_journey_id to a temporary table that acts as a processing queue?
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 147 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsy0kaD-IX95JH4gQU:-NOsy0kb41TZBE3rXoRN:bxa8vc8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L147)):*
> ```TSQL
>   RETURN NULL;
> END;
> $$;
> ```

same as above, could you create a comment for this function?
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 157 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsyV5bEKElRfj2k6LY:-NOsyV5bEKElRfj2k6LZ:b-5uerq) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L157)):*
> ```TSQL
>   -- RAISE NOTICE 'passing_times.validate_passing_time_sequences()';
> 
>   FOR row_validation_data IN (
> ```

let's add a comment here, like "retrieving all the vehicle_journey_ids and journey_pattern_ref_ids from the queues and run them through the validation function"
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 178 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOszM8D9RXf-fQY27z1:-NOszM8E4jdFwAt7fow8:b-8nvhcm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L178)):*
> ```TSQL
>     IF (row_validation_data.stop_order_is_valid = false)
>     THEN
>       RAISE EXCEPTION 'passing times and their matching stop points must be in same order';
> ```

could you also print the vehicle_journey_id for this exception? Helps with debugging...
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 186 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOszppK9_JOXyRktE3t:-NOszppK9_JOXyRktE3u:b-8nvhcm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L186)):*
> ```TSQL
>     )
>     THEN
>       RAISE EXCEPTION 'first passing time must not have arrival_time set.';
> ```

could you also print the vehicle_journey_id for this exception? Helps with debugging...
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 194 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOszr-GCRm260Mi4u3I:-NOszr-GCRm260Mi4u3J:b-8nvhcm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L194)):*
> ```TSQL
>     )
>     THEN
>       RAISE EXCEPTION 'last passing time must not have departure_time set.';
> ```

could you also print the vehicle_journey_id for this exception? Helps with debugging...
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 207 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt-8le5f17pWlR0SOi:-NOt--Nb1js1YQqQNXt7:b-8nvhcm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L207)):*
> ```TSQL
>     )
>     THEN
>       RAISE EXCEPTION 'all passing time that are not first or last in the sequence must have both departure and arrival time defined.';
> ```

could you also print the vehicle_journey_id for this exception? Helps with debugging...
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 241 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt0DSM69ccQ2dXSmqV:-NOt0DSM69ccQ2dXSmqW:b-s274ed) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L241)):*
> ```TSQL
> COMMENT ON TRIGGER queue_validate_passing_times_sequence_on_pt_update_trigger ON passing_times.timetabled_passing_time
> IS 'Trigger to queue validation of passing ti [...]

2023-02-22 12:24 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149)* status: 0 of 19 files reviewed, 28 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/generic/timetablesdb/datasets/types.ts` line 63 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt2yK7B3uEelkCF884:-NOt2yK7B3uEelkCF885:b-hs0z93) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/types.ts#L63)):*
> ```XML
> ];
> 
> export type TimetabledPassingTimes = {
> ```

let's not make the type name plural
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/day-types.ts` line 1 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt1N3V4Ml1jryOCzb_:-NOt1N3V4Ml1jryOCzba:b-q76j70) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/day-types.ts#L1)):*
> ```XML
> // These are populated in mirations.
> ```

typo: migrations
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/journey-pattern-refs.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt1wym-1OpBL0FSg0j:-NOt1wym-1OpBL0FSg0k:b-kps2yl) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/journey-pattern-refs.ts#L4)):*
> ```XML
> import { JourneyPatternRef } from '../types';
> 
> export const journeyPatternRefsByName = {
> ```

you could already set the type here:
```
export const journeyPatternRefsByName: Record<string, JourneyPatternRef> = {...}
```

then you wouldn't need to do the type casting below for journeyPatternRefs
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/passing-times.ts` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt2d9M27Ql88rB7aAL:-NOt2d9M27Ql88rB7aAM:bqxqvi1) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/passing-times.ts#L7)):*
> ```XML
> 
> export const timetabledPassingTimesByName = {
>   // Journey 1, outbound.
> ```

this would've been nicer and more readable if it was built by a generator function... well, let's leave it like this for now, it's not necessarily in the scope of this PR
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/passing-times.ts` line 172 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt2J-IDgVocXuRnACm:-NOt2J-IDgVocXuRnACn:b-d0fgcw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/passing-times.ts#L172)):*
> ```XML
>   },
> };
> export const timetabledPassingTimes: TimetabledPassingTimes[] = Object.values(
> ```

same as above: you could already set the typing for the timetabledPassingTimesByName variable above as `Record<string, TimetabledPassingTime>`
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/stop-points.ts` line 8 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt3AE68t9a009LoZcI:-NOt3AE68t9a009LoZcJ:b-ya2lhe) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/stop-points.ts#L8)):*
> ```XML
> export const scheduledStopPointsInJourneyPatternRefByName = {
>   route123OutboundStop1: {
>     scheduled_stop_point_in_journey_pattern_ref_id:
> ```

same as above, would've been nicer with a generator function. But fine for now...
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/stop-points.ts` line 66 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt3FfFDjPfzBxLuqdx:-NOt3FfFDjPfzBxLuqdy:b7htnlq) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/stop-points.ts#L66)):*
> ```XML
> };
> 
> export const scheduledStopPointsInJourneyPatternRef: ScheduledStopInJourneyPatternRef[] =
> ```

same as above: you could already set the typing for the sspinjpRefByName variable above as `Record<string, ScheduledStopInJourneyPatternRef>`
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/vehicle-journeys.ts` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt3Q6S-Vd4WKtSSpAQ:-NOt3Q6S-Vd4WKtSSpAR:bnj7hl0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/vehicle-journeys.ts#L31)):*
> ```XML
>   },
> };
> export const vehicleJourneys: VehicleJourney[] = Object.values(
> ```

same as above
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/vehicle-schedules-frames.ts` line 27 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt3RT0A80grftUH6aa:-NOt3RT0A80grftUH6ab:bnj7hl0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/vehicle-schedules-frames.ts#L27)):*
> ```XML
> };
> 
> export const vehicleScheduleFrames: VehicleScheduleFrame[] = Object.values(
> ```

same as above
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/vehicle-service-blocks.ts` line 21 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt3WKl1m0CrWDLuTqo:-NOt3WKl1m0CrWDLuTqp:bnj7hl0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/vehicle-service-blocks.ts#L21)):*
> ```XML
>   },
> };
> export const vehicleServiceBlocks: VehicleServiceBlock[] = Object.values(
> ```

same as above
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/vehicle-services.ts` line 28 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt3dnj00Ih_s1KIyk5:-NOt3dnj00Ih_s1KIyk6:bnj7hl0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/vehicle-services.ts#L28)):*
> ```XML
>   },
> };
> export const vehicleServices: VehicleService[] = Object.values(
> ```

same as above


<!-- Sent from Reviewable.io -->

2023-02-22 12:36 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149)* status: 0 of 19 files reviewed, 34 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/timetablesdb-dump.sql` line 903 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt55VS-5QLoYiu0m3C:-NOt55VS-5QLoYiu0m3D:b-ehy00g) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/timetablesdb-dump.sql#L903)):*
> ```TSQL
>     passing_time interval GENERATED ALWAYS AS (COALESCE(departure_time, arrival_time)) STORED NOT NULL,
>     CONSTRAINT arrival_or_departure_time_exists CHECK (((arrival_time IS NOT NULL) OR (departure_time IS NOT NULL))),
>     CONSTRAINT departure_not_after_arrival CHECK (((arrival_time IS NULL) OR (departure_time IS NULL) OR (arrival_time <= departure_time)))
> ```

the name is incorrect: it should be arrival_not_after_departure. Meaning that the bus shouldn't depart before it has arrived at a stop
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt6ASB73lwr1lPWqTI:-NOt6ASB73lwr1lPWqTJ:bziiioc) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L16)):*
> ```XML
> import { post } from 'request-promise';
> 
> describe('Vehicle journey passing time validation', () => {
> ```

this is a very good set of tests for checking what happens when you update a timetabled passing time entity. Do you have energy to create a test set also for the insert operation or should we just create a github issue about it to be done later? :)
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 95 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt4ZMD-qiToHel3N7J:-NOt4ZMEBlnsDsrwuRmZ:b-sbgogi) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L95)):*
> ```XML
>   };
> 
>   it('should accept a valid passing time', async () => {
> ```

could also add a test that if setting a stop's passing time to the same as the next one's, it should succeed. At least I think that's a valid option
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 161 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt4vCZ21JrSuHO2WCg:-NOt4vCZ21JrSuHO2WCh:b-kc90x1) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L161)):*
> ```XML
>   });
> 
>   it('should not accept passing time with arrival_time < departure_time', async () => {
> ```

right the other way around: arrival_time > departure_time
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 319 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt62j1Aum0lDtDVjVk:-NOt62j1Aum0lDtDVjVl:bb7phvt) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L319)):*
> ```XML
>   });
> 
>   it('should trigger validationon scheulded stop point in journey pattern ref modifications', async () => {
> ```

typo
___
*[`test/hasura/jest/testers.ts` line 19 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt6eeyBEavpiWG4cQe:-NOt6ef14RR4H9aaXGzN:b-xe35rs) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/jest/testers.ts#L19)):*
> ```XML
> 
> function areDurationAndStringEqual(a: unknown, b: unknown) {
>   const comparingDateAndDateTime =
> ```

copy-paste :) maybe `comparingDurationAndString`?


<!-- Sent from Reviewable.io -->

2023-02-22 12:41 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149)* status: 0 of 19 files reviewed, 35 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt7ElH4_jk_iJ0PFW0:-NOt7ElH4_jk_iJ0PFW1:bc1v7o5) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L40)):*
> ```TSQL
>       combo.*,
>       combo.passing_time > previous_combo.passing_time AS is_after_previous
>     FROM traversal as previous_combo
> ```

also, let's actually check that:
```
combo.arrival_time >= previous_combo.departure_time AS is_after_previous
```

because the passing_time is a calculated field that wouldn't work for the following case:

```
stop1: arrival_time = 10:00, departure_time = 10:05 (-> passing_time = 10:05)
stop2: arrival_time = 10:02, departure_time = 10:07 (-> passing_time = 10:07)
```

so even though we could technically arrive to stop2 before we departed from stop1, the passing_time checks wouldn't notice that

... also let's add an integration test about this case ;)


<!-- Sent from Reviewable.io -->

2023-02-22 14:22 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149)* status: 0 of 19 files reviewed, 34 unresolved discussions (waiting on @pallost)

___
*[`README.md` line 120 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOst75V2Ngp7EUnX3hy:-NOtPcEE0MbHHpP1jE-7:bhp90gm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/README.md#L120)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

also remember that queries are run a different way in case there's actually lots of data in the database. The optimizer might choose to run the queries using different indexes compared to how it would run it in case of little amount of data. So trying to optimize your queries now, without any much seed data might be misleading
</blockquote></details>

Yep. Didn't bother analyzing much because of that. Thought I'd still document this process since it was news to me at least.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 39 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsv6kc6CoLeslAv1cG:-NOtQDUUEjGAJmThRvpz:b-hmsasx) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L39)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think we could also allow `>=` relation here (so that the same passing time is marked for multiple stops)
</blockquote></details>

Good point, I see no harm in that, will change.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt7ElH4_jk_iJ0PFW0:-NOtQfhRCqtqUH8dUg4x:boojcqy) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L40)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

also, let's actually check that:
```
combo.arrival_time >= previous_combo.departure_time AS is_after_previous
```

because the passing_time is a calculated field that wouldn't work for the following case:

```
stop1: arrival_time = 10:00, departure_time = 10:05 (-> passing_time = 10:05)
stop2: arrival_time = 10:02, departure_time = 10:07 (-> passing_time = 10:07)
```

so even though we could technically arrive to stop2 before we departed from stop1, the passing_time checks wouldn't notice that

... also let's add an integration test about this case ;)
</blockquote></details>

I'm not sure if this is a realistic case, that the bus would arrive to stop 2 before departing from stop 1. Let's see what Jenö has to say.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 107 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsxB7NDn_lJu5ejjvy:-NOtQs4rC04ye1Gmq0GB:bouxli2) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L107)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I needed to look this up. Could you please put a comment here that this "already_validated" variable is scoped only for the current transaction
</blockquote></details>

Will do, think I had to double check that as well. This specific pattern was copied from existing migrations.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 130 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsxeTz-yBGVvxU81zX:-NOtRCy12AiRUTlJXcH-:b9jue4b) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L130)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you create a comment for this function? Do I understand it correctly that it just adds the modified table's vehicle_journey_id to a temporary table that acts as a processing queue?
</blockquote></details>

Sure. Yep, that's what it does.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 157 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsyV5bEKElRfj2k6LY:-NOtRMoz-r08talCO8IT:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L157)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's add a comment here, like "retrieving all the vehicle_journey_ids and journey_pattern_ref_ids from the queues and run them through the validation function"
</blockquote></details>

:thumbsup: 
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 178 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOszM8D9RXf-fQY27z1:-NOtR_SkAoMTP_nwof-l:b-a2o694) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L178)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you also print the vehicle_journey_id for this exception? Helps with debugging...
</blockquote></details>

Yep, good point. Or probably just add it to the exception message.
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/journey-pattern-refs.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt1wym-1OpBL0FSg0j:-NOtRr9lB22iMTUooXcM:bq99roy) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/journey-pattern-refs.ts#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could already set the type here:
```
export const journeyPatternRefsByName: Record<string, JourneyPatternRef> = {...}
```

then you wouldn't need to do the type casting below for journeyPatternRefs
</blockquote></details>

Could, but would rather not. Had originally set it like that, but reverted to this. Rationale: when defining these variables without the type, IDE let's you jump straight to the property definitions in this object from other files, which does not work if you set up the Record type. On UI side these `byname` records were set up similarly (by coincidence or on purpose, dunno).
___
*[`test/hasura/generic/timetablesdb/datasets/defaultSetup/passing-times.ts` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt2d9M27Ql88rB7aAL:-NOtS4w5AtpRAgFeegqS:b-q6yf5z) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/defaultSetup/passing-times.ts#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this would've been nicer and more readable if it was built by a generator function... well, let's leave it like this for now, it's not necessarily in the scope of this PR
</blockquote></details>

Yep, this is absolutely horrible. Didn't want to start implementing yet-another-test-data-builder-that-is-only-used-in-one-place though, at least not before getting opinions and seeing if same pattern could work elsewhere, so went with similar plain data approach as done elsewhere.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 16 at r2](h [...]

2023-02-27 08:40 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149)* status: 0 of 19 files reviewed, 30 unresolved discussions (waiting on @pallost)

___
*[`migrations/timetablesdb-dump.sql` line 903 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt55VS-5QLoYiu0m3C:-NOuLbkSBIsvL0xS1Sp1:b387xvy) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/timetablesdb-dump.sql#L903)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the name is incorrect: it should be arrival_not_after_departure. Meaning that the bus shouldn't depart before it has arrived at a stop
</blockquote></details>

:facepalm: :thumbsup: 
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 19 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsw1o3BkjnSFUVSVaX:-NOuKWJaCaOXaE1Tot3c:b-31xhq9) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L19)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I didn't notice that you'd use the `ssp.*` columns below. I think it could be removed from here
</blockquote></details>

Damn, good catch.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt7ElH4_jk_iJ0PFW0:-NPH0p8P62I2Duiu1IhF:b9evvn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L40)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I'm not sure if this is a realistic case, that the bus would arrive to stop 2 before departing from stop 1. Let's see what Jenö has to say.
</blockquote></details>

This case is now prevented, and added a test to verify the behavior.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 147 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOsy0kaD-IX95JH4gQU:-NOuU0_25LoVvxAiN7hG:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L147)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

same as above, could you create a comment for this function?
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 186 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOszppK9_JOXyRktE3t:-NOuRZ4t199sNoUo9zbV:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L186)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you also print the vehicle_journey_id for this exception? Helps with debugging...
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 194 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOszr-GCRm260Mi4u3I:-NOuRbmp95hQSOp4U0iX:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L194)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you also print the vehicle_journey_id for this exception? Helps with debugging...
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 207 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt-8le5f17pWlR0SOi:-NOuRdJj6Mp_Avmu6jOu:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L207)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you also print the vehicle_journey_id for this exception? Helps with debugging...
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 242 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt-dC62MMcEIhthsb9:-NOuGsYu93g4BRwVkWH2:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L242)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

indent
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 259 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt0QSq3IHZjmhh5e8x:-NOuGut0DvKqQ1ujZPRX:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L259)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

indent
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql` line 260 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt0S3T0srYNKHRc8NO:-NOuI8BYBxZZYBdal-xG:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/migrations/generic/timetables/2000000000001_R_after_migrate_create_passing_times/up.sql#L260)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.



_Code quote:_
```TSQL
queue_validate_passing_times_sequence_on_ssp_insert_trigger
```
___
*[`test/hasura/generic/timetablesdb/datasets/types.ts` line 63 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NOt2yK7B3uEelkCF884:-NOuGNB5BIPvD3OVYHeP:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/ab6d8687489b04dbbd97887a8aab9d373fc6e368/test/hasura/generic/timetablesdb/datasets/types.ts#L63)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's not make the type name plural
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 09:20 UTC, pallost approved these changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149)* status: 0 of 21 files reviewed, 9 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/timetablesdb-dump.sql` line 693 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPM6H_v0ecMxzYvyECU:-NPM6H_v0ecMxzYvyECV:b-fuwqxi) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/migrations/timetablesdb-dump.sql#L693)):*
> ```TSQL
>       -- 2. via timetabled_passing_times and related scheduled_stop_point_in_journey_pattern_ref
>       -- Let's ensure that vehicle_journey and its timetabled_passing_times reference same journey_pattern_ref
>       EVERY(vehicle_journey_journey_pattern_ref_id = stop_point_journey_pattern_ref_id) AS coherent_journey_pattern_refs
> ```

good addition, thanks!
___
*[`migrations/timetablesdb-dump.sql` line 917 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPM6hdSCdDdQqcDbDgm:-NPM6hdSCdDdQqcDbDgn:bdfbb3a) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/migrations/timetablesdb-dump.sql#L917)):*
> ```TSQL
> --
> 
> CREATE UNIQUE INDEX passing_times_timetabled_passing_time_vehicle_journey_id_schedu ON passing_times.timetabled_passing_time USING btree (vehicle_journey_id, scheduled_stop_point_in_journey_pattern_ref_id);
> ```

as you can see here in the dump, the objects' names in postgresql get clipped after 64 characters. In some rare cases it can cause issues... Could you choose a more concise one for this index? Maybe just remove the schema prefix...
___
*[`migrations/generic/timetables/1677249596839_vehicle_journey_scheduled_stop_point_unique_index/up.sql` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPM7xiq1aMYamljVVv0:-NPM7xiq1aMYamljVVv1:b3k1cpx) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/migrations/generic/timetables/1677249596839_vehicle_journey_scheduled_stop_point_unique_index/up.sql#L2)):*
> ```TSQL
> CREATE UNIQUE INDEX passing_times_timetabled_passing_time_vehicle_journey_id_scheduled_stop_point_in_journey_pattern_ref_id_unique_idx
> ON passing_times.timetabled_passing_time USING btree (vehicle_journey_id, scheduled_stop_point_in_journey_pattern_ref_id);
> ```

could you add a quick comment here, something like "The unique index makes sure that every stop in the journey pattern sequence can be used once. This however does not affect loops as those are separate rows within the journey pattern."
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 438 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMGvpK0mlArZnPOSiT:-NPMGvpK0mlArZnPOSiU:b-iairyj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L438)):*
> ```XML
>   });
> 
>   it('should trigger validation on passing time insert', async () => {
> ```

let's move insert, update and delete operation tests at least to their own "describe" blocks or could even consider splitting them to separate files
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 455 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMBFZYC0uAHgzquhyY:-NPMBFZYC0uAHgzquhyZ:b-22yzad) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L455)):*
> ```XML
> 
>     const insertQuery = `
>       mutation {
> ```

let's rather move this to its own buildMutation function like above, less bloat for the test code
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 493 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMI-yKCptwi0ZOJv-l:-NPMI-yKCptwi0ZOJv-m:b-xwnjqq) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L493)):*
> ```XML
>   });
> 
>   it('should trigger validation on passing time delete and fail an invalid sequence', async () => {
> ```

it's nice that this setup fails but I'm a bit worried if there's a flow with which we could actually delete the first passing time row and update the second so that it would pass the checks. Could you test this manually please? Not necessary to test this case in an integration test in my opinion...

To execute multiple mutations in the same transaction, here's a Hasura article: https://hasura.io/docs/latest/mutations/postgres/multiple-mutations/

basically just group several operations under the same mutation block, something like:

```
mutation {
  timetables {
   timetables_delete_passing_times_timetabled_passing_time_by_pk(<id of first passing time>) {...}
   timetables_update_passing_times_timetabled_passing_time_by_pk(<id of second passing time>, _set: {arrival_time = null})
  }
}
```
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 499 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMBNahAmM4sSvUBkFc:-NPMBNahAmM4sSvUBkFd:b-22yzad) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L499)):*
> ```XML
>       timetabledPassingTimesByName.v1MonFriJourney2Stop3;
> 
>     const deleteQuery = `
> ```

let's rather move this to its own buildMutation function like above, less bloat for the test code
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 519 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMHmeMBUxuh6xE96a9:-NPMHmeMBUxuh6xE96aA:b-hq7bfh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L519)):*
> ```XML
>     const response = await postQuery(deleteQuery);
> 
>     expectErrorResponse('last passing time must not have departure_time se')(
> ```

"se"? :)
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 533 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMJHXZBHAsY_bF7UDs:-NPMJHXZBHAsY_bF7UDt:byj27t5) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L533)):*
> ```XML
>       scheduledStopPointsInJourneyPatternRefByName.route123OutboundStop3;
> 
>     const updateQuery = buildUpdateStopPointsMutation([
> ```

could you write a comment here that you're swapping the sequence numbers for testStopPoint and nextStopPoint?


<!-- Sent from Reviewable.io -->

2023-02-28 15:35 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149)* status: 0 of 21 files reviewed, 9 unresolved discussions (waiting on @pallost)

___
*[`migrations/timetablesdb-dump.sql` line 917 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPM6hdSCdDdQqcDbDgm:-NPM_B6u4FxBMCeEuan_:b7paogy) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/migrations/timetablesdb-dump.sql#L917)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

as you can see here in the dump, the objects' names in postgresql get clipped after 64 characters. In some rare cases it can cause issues... Could you choose a more concise one for this index? Maybe just remove the schema prefix...
</blockquote></details>

Hmm, nice behavior... Will fix, was just blindly following the previous convention.
___
*[`migrations/generic/timetables/1677249596839_vehicle_journey_scheduled_stop_point_unique_index/up.sql` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPM7xiq1aMYamljVVv0:-NPN7PC88wMSB7vnrxso:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/migrations/generic/timetables/1677249596839_vehicle_journey_scheduled_stop_point_unique_index/up.sql#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you add a quick comment here, something like "The unique index makes sure that every stop in the journey pattern sequence can be used once. This however does not affect loops as those are separate rows within the journey pattern."
</blockquote></details>

:thumbsup: 
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 438 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMGvpK0mlArZnPOSiT:-NPNdWKD3DLkcJ7MuuGJ:bb1c9gt) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L438)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's move insert, update and delete operation tests at least to their own "describe" blocks or could even consider splitting them to separate files
</blockquote></details>

Splitting to describes, in separate commit to avoid rebase hell. These test same piece of code so belong to same file.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 455 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMBFZYC0uAHgzquhyY:-NPNOmH89LehsBFRGZ1A:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L455)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's rather move this to its own buildMutation function like above, less bloat for the test code
</blockquote></details>

Done.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 493 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMI-yKCptwi0ZOJv-l:-NPNOnhn7jBgpwQ0T75a:b-uyxjmn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L493)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's nice that this setup fails but I'm a bit worried if there's a flow with which we could actually delete the first passing time row and update the second so that it would pass the checks. Could you test this manually please? Not necessary to test this case in an integration test in my opinion...

To execute multiple mutations in the same transaction, here's a Hasura article: https://hasura.io/docs/latest/mutations/postgres/multiple-mutations/

basically just group several operations under the same mutation block, something like:

```
mutation {
  timetables {
   timetables_delete_passing_times_timetabled_passing_time_by_pk(<id of first passing time>) {...}
   timetables_update_passing_times_timetabled_passing_time_by_pk(<id of second passing time>, _set: {arrival_time = null})
  }
}
```
</blockquote></details>

Since the validation triggers at end of transaction, operations like you described work fine. Will just add a test for this, seems important enough.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 499 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMBNahAmM4sSvUBkFc:-NPNPtcw3q5xwtvhQJEP:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L499)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's rather move this to its own buildMutation function like above, less bloat for the test code
</blockquote></details>

Done.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 519 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMHmeMBUxuh6xE96a9:-NPNPxKS0Gg1EUQtr48S:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L519)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

"se"? :)
</blockquote></details>

Done.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts` line 533 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/149#-NPMJHXZBHAsY_bF7UDs:-NPNPz26EtIMrRP2cnkG:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/50c8e844ef725ebd9b746efaef04a183ec64e707/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-journey/passing-times.spec.ts#L533)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you write a comment here that you're swapping the sequence numbers for testStopPoint and nextStopPoint?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-01 06:49 UTC, merged