Add denormalized table for references between vehicle journey and journey pattern
HSLdevcom/jore4-hasura pull request #158
Opened 2023-03-15 08:30 UTC by Leitsi

2023-03-15 10:32 UTC, pallost reviewed
> Reviewed 16 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 16 of 25 files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`metadata/generic/databases/timetables/tables/vehicle_service_journey_patterns_in_vehicle_service.yaml` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZPygN6PJQ31YM-12t:-NQZPygN6PJQ31YM-12u:b69effb) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/metadata/generic/databases/timetables/tables/vehicle_service_journey_patterns_in_vehicle_service.yaml#L18)):*
> ```YAML
>           name: journey_pattern
>           schema: journey_pattern
>     name: journey_pattern_instance
> ```

could you also add the remote_relationship from the other direction? From the networkdb's journey_pattern.journey_pattern table we should reference this table within the timetablesdb so that the UI could run queries in this direction too.
___
*[`migrations/generic/default/1610000000000_squashed_dump/up.sql` line 282 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZQwis8A6OS0qMHRVv:-NQZQwis8A6OS0qMHRVw:ba4t74x) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/migrations/generic/default/1610000000000_squashed_dump/up.sql#L282)):*
> ```TSQL
> COMMENT ON COLUMN service_pattern.scheduled_stop_point.direction IS 'The direction(s) of traffic with respect to the digitization, i.e. the direction of the specified line string.';
> COMMENT ON COLUMN service_pattern.scheduled_stop_point.label IS 'The label is the short code that identifies the stop to the passengers. There can be at most one stop with the same label at a time. The label matches the GTFS stop_code.';
> COMMENT ON COLUMN service_pattern.scheduled_stop_point.validity_start IS 'start of the operating date span in the scheduled stop point''s local time(inclusive).';
> ```

whitespace :) `time (inclusive)`


<!-- Sent from Reviewable.io -->

2023-03-15 11:00 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 16 of 25 files reviewed, 8 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/generic/timetables/2000000000003_R_add_journey_patterns_in_vehicle_service_sync_objects/up.sql` line 79 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZvRw_2xUaQEO9Guxp:-NQZvRw_2xUaQEO9Guxq:b4yive3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/migrations/generic/timetables/2000000000003_R_add_journey_patterns_in_vehicle_service_sync_objects/up.sql#L79)):*
> ```TSQL
> DROP TRIGGER IF EXISTS refresh_jps_in_vs_on_vs_modified_trigger ON vehicle_service.vehicle_service;
> CREATE CONSTRAINT TRIGGER refresh_jps_in_vs_on_vs_modified_trigger
>   AFTER UPDATE OR INSERT OR DELETE ON vehicle_service.vehicle_service
> ```

I don't think you need to run this trigger on UPDATE
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZs8BJ2BTcvjmwyWke:-NQZs8BJ2BTcvjmwyWkf:brrkfd3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L1)):*
> ```XML
> import { hasuraRequestTemplate, timetablesDbConfig } from '@config';
> ```

there's a typo in the name of the folder: "vehi*c*le-schedule"

also, let's call this test suite rather "journey-patterns-in-vehicle-service.spec.ts" as this doesn't have much to do with journey pattern refs
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZrwWO6cMm9aXJBEij:-NQZrwWO6cMm9aXJBEik:b-53w5jj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L34)):*
> ```XML
>   beforeEach(() => setupDb(dbConnection, defaultGenericTimetablesDbData));
> 
>   const buildPartialInsertVehicleJourneyMutation = (
> ```

I don't think you need to name these as "partial"
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 197 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZt-VB7h_sS0iplkzs:-NQZt-VB7h_sS0iplkzt:brpbbt3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L197)):*
> ```XML
>           journeyPatternRefsByName.route123Outbound.journey_pattern_ref_id,
>       };
>       const insertMutation = `mutation {
> ```

you could move this "mutation {...}" wrapping to its own tiny function for clarity
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 396 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZttG50NxJ3nTEwWF7:-NQZttG50NxJ3nTEwWF8:bb7phvt) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L396)):*
> ```XML
>           },
>           // ...because it was moved to another block,
>           // which is in different veihcle service -> new row.
> ```

typo
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 435 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZuTBnAhuveRGKWTms:-NQZuTBnAhuveRGKWTmt:b-gt3ht6) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L435)):*
> ```XML
>         ]),
>       );
>     });
> ```

could you add a test where you insert a brand new vehicle service with a block and a vehicle journey?
Also should add a test where an existing vehicle service is deleted.
(IMHO the current tests don't show this behaviour too clearly. I know that when inserting the test dataset data, this trigger gets executed, but would be nice to see this explicitly)


<!-- Sent from Reviewable.io -->

2023-03-15 12:38 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 16 of 25 files reviewed, 7 unresolved discussions (waiting on @pallost)

___
*[`metadata/generic/databases/timetables/tables/vehicle_service_journey_patterns_in_vehicle_service.yaml` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZPygN6PJQ31YM-12t:-NQ_4khzA60lRYE0O9_7:b-6kdfdn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/metadata/generic/databases/timetables/tables/vehicle_service_journey_patterns_in_vehicle_service.yaml#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you also add the remote_relationship from the other direction? From the networkdb's journey_pattern.journey_pattern table we should reference this table within the timetablesdb so that the UI could run queries in this direction too.
</blockquote></details>

Sure, had forgotten about that, added.
___
*[`migrations/generic/default/1610000000000_squashed_dump/up.sql` line 282 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZQwis8A6OS0qMHRVv:-NQ_2QFYA104FDt_9Xuh:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/migrations/generic/default/1610000000000_squashed_dump/up.sql#L282)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

whitespace :) `time (inclusive)`
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000003_R_add_journey_patterns_in_vehicle_service_sync_objects/up.sql` line 79 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZvRw_2xUaQEO9Guxp:-NQZxbp68xHE-oplUiZ5:brds43t) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/migrations/generic/timetables/2000000000003_R_add_journey_patterns_in_vehicle_service_sync_objects/up.sql#L79)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think you need to run this trigger on UPDATE
</blockquote></details>

:thumbsup:  true, fixed.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZs8BJ2BTcvjmwyWke:-NQ_32jJ-1l_z9gHUruU:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there's a typo in the name of the folder: "vehi*c*le-schedule"

also, let's call this test suite rather "journey-patterns-in-vehicle-service.spec.ts" as this doesn't have much to do with journey pattern refs
</blockquote></details>

Done.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZrwWO6cMm9aXJBEij:-NQZxkTDEX-Y35YgoVTn:b-ifevsn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L34)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think you need to name these as "partial"
</blockquote></details>

Sure, can drop it. Rationale was that wanted to make some distinction to builders that return mutations that can be ran as-is (like we have in most other suites), and they are generally named `build<table name><operation>Mutation`. But maybe not a problem here because all builders in this suite work in a similar way.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 197 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZt-VB7h_sS0iplkzs:-NQZzhOWCXIBGG_OQxku:b-7nno2x) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L197)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could move this "mutation {...}" wrapping to its own tiny function for clarity
</blockquote></details>

Yep, this removed a lot of clutter, :thumbsup: 
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 435 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZuTBnAhuveRGKWTms:-NQ_5kXF6zz19-BiWVkf:b-1sn1sq) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L435)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you add a test where you insert a brand new vehicle service with a block and a vehicle journey?
Also should add a test where an existing vehicle service is deleted.
(IMHO the current tests don't show this behaviour too clearly. I know that when inserting the test dataset data, this trigger gets executed, but would be nice to see this explicitly)
</blockquote></details>

Thought about this, but decided not to. I think current tests provide good enough coverage. Also would require too much additional setup code just for this case, for my taste.

For vehicle service deletion would also have to remove the vehicle journey in same transaction, and we have a test for that already.


<!-- Sent from Reviewable.io -->

2023-03-16 06:02 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 13 of 26 files reviewed, 7 unresolved discussions (waiting on @pallost)

___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts` line 435 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NQZuTBnAhuveRGKWTms:-NQd-Jhx6UmLCSyM7i3-:b-rfb8uy) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1b0eafebbce73833a6c39e5efd70621ff397299c/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehile-schedule/journey-pattern-refs.spec.ts#L435)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Thought about this, but decided not to. I think current tests provide good enough coverage. Also would require too much additional setup code just for this case, for my taste.

For vehicle service deletion would also have to remove the vehicle journey in same transaction, and we have a test for that already.
</blockquote></details>

Actually, I think the related ON INSERT and ON DELETE triggers can be removed as well. Since no reference to journey_pattern is created/removed unless vehicle_journey is inserted/deleted.


<!-- Sent from Reviewable.io -->

2023-03-21 14:05 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 15 of 47 files reviewed, 21 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 265 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3NER92Kd0PZ7AqhHc:-NR3NER92Kd0PZ7AqhHd:bp5a80q) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql#L265)):*
> ```TSQL
> CREATE CONSTRAINT TRIGGER process_queued_validation_on_vj_trigger
>   -- NOTE: the DELETE does not currently have related queue trigger.
>   -- That is because we only need i for refresh_journey_patterns_in_vehicle_service,
> ```

typo: it
___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 283 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3NR0I5HLnDYDjEVrY:-NR3NR0I5HLnDYDjEVrZ:b2he1yc) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql#L283)):*
> ```TSQL
>   EXECUTE FUNCTION internal_utils.execute_queued_validations();
> COMMENT ON TRIGGER process_queued_validation_on_jpr_trigger ON journey_pattern.journey_pattern_ref
> IS 'Trigger to execute queued validations that were registered earlier by statement level triggers';
> ```

nicely done, well commented and easy to follow the logic!
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 18 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3Oztj5DkVT1B4_Z_4:-NR3Oztj5DkVT1B4_Z_5:b-r9u3p1) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L18)):*
> ```TSQL
>   -- Find out which rows we need to check.
>   -- Only modified rows and those they could possibly conflict with need to be checked. This includes:
>   -- 1. modified VSFs
> ```

note: we shouldn't check collisions for draft and staging priorities. Only for standard, temporary and special (the substitute operating day priority doesn't concern this constraint)

Let's create a constant function, like this:
```
CREATE FUNCTION internal_utils.const_priority_draft() RETURNS integer
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    AS $$SELECT 30$$;
```

then you can filter the relevant vehicle schedule frames by `WHERE priority < const_priority_draft()`
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 44 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3QaTs-4H8fniGzAoR:-NR3QaTs-4H8fniGzAoS:b-obdvey) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L44)):*
> ```TSQL
>     FROM vehicle_service.journey_patterns_in_vehicle_service
>     JOIN vehicle_service.vehicle_service USING (vehicle_service_id)
>     JOIN journey_pattern.journey_pattern_ref USING (journey_pattern_id)
> ```

do you need this join with the journey_pattern_ref table? You already have the journey_pattern_id available from the journey_patterns_in_vehicle_service table
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 48 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3QPRU1jbvy84JoIM1:-NR3QPRV8dr4yDVd-Xf8:b4p6p2n) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L48)):*
> ```TSQL
>     JOIN service_calendar.day_type_active_on_day_of_week USING (day_type_id)
>     WHERE (
>       journey_pattern_id IN (SELECT * FROM journey_patterns_to_check)
> ```

does the = ANY() syntax work in this case?
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 74 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3SFgy-iHZwrV6wAD5:-NR3SFgy-iHZwrV6wAD6:bql9mqa) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L74)):*
> ```TSQL
> IS 'Returns information on all schedules that are overlapping.
>   Two vehicle_schedule_frames will be considered overlapping if they have:
>   - same priority
> ```

...(excluding draft and staging priorities)
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 92 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3T5gDD7UW9nvud-9t:-NR3T5gDD7UW9nvud-9u:b45r43r) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L92)):*
> ```TSQL
>   WITH modified_vehicle_schedule_frame_ids AS (
>     SELECT vehicle_schedule_frame_id
>     FROM modified_vehicle_journey
> ```

imho UNIONs would be easier to read, but I guess this works too...
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 110 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3Tx4K1iEAbnQ5DCkC:-NR3Tx4K1iEAbnQ5DCkD:b-agaexp) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L110)):*
> ```TSQL
>     -- Note, this includes only one of the conflicting rows. There might be multiple.
>     SELECT format(
>       'vehicle schedule frame %s and vehicle schedule frame %s, priority %s, journey_pattern_id %s, overlapping on %s on weekday %s',
> ```

well, technically this is "day of week" and not weekday :)



_Code quote:_
```TSQL
weekday
```
___
*[`migrations/generic/timetables/2000000001000_R_after_migrate_execute_queued_validations/up.sql` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3UBNiEt634CTbNFKv:-NR3UBNiEt634CTbNFKw:bg7wnp6) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000001000_R_after_migrate_execute_queued_validations/up.sql#L15)):*
> ```TSQL
> 
>   -- RAISE LOG 'before vehicle_schedule.validate_queued_schedules_uniqueness()';
>   PERFORM vehicle_schedule.validate_queued_schedules_uniqueness();
> ```

I guess in the future we should move the timetabled passing time triggers and validations also to this setup...?


<!-- Sent from Reviewable.io -->

2023-03-21 14:07 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 15 of 47 files reviewed, 21 unresolved discussions (waiting on @pallost)

___
*[`migrations/generic/timetables/1678451029539_add-denormalized-jps-in-vs-table/up.sql` line 7 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3GB3v3yoi4cViX88j:-NR3ORszEPA3eNb34xAA:b-cblw2k) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/1678451029539_add-denormalized-jps-in-vs-table/up.sql#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

If I'm not mistaken, this creates an index that's only efficient to be traversed from the left columns (so efficient for vehicle service ids, but not with journey pattern ids). So if we wanted to do joins from this table to the journey_pattern_ref table, it won't be efficient. Maybe we should create an index just for the journey_pattern_id column, separately...

From the documentation:
```
A multicolumn B-tree index can be used with query conditions that involve any subset of the index's columns, but the index is most efficient when there are constraints on the leading (leftmost) columns. The exact rule is that equality constraints on leading columns, plus any inequality constraints on the first column that does not have an equality constraint, will be used to limit the portion of the index that is scanned. Constraints on columns to the right of these columns are checked in the index, so they save visits to the table proper, but they do not reduce the portion of the index that has to be scanned. For example, given an index on (a, b, c) and a query condition WHERE a = 5 AND b >= 42 AND c < 77, the index would have to be scanned from the first entry with a = 5 and b = 42 up through the last entry with a = 5. Index entries with c >= 77 would be skipped, but they'd still have to be scanned through. This index could in principle be used for queries that have constraints on b and/or c with no constraint on a — but the entire index would have to be scanned, so in most cases the planner would prefer a sequential table scan over using the index.
```
</blockquote></details>

Yep, that's how it works. Think there was already joins by journey_pattern_id, so let's add an index for that, :thumbsup: 
___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 1 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3IhuiDV06mUy3a5in:-NR3Q9Wf4972ZvM0GPaN:bmfbq65) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

just a note here: renaming the repeatable migrations like how you've done right now didn't cause issues, because the same timestamps are still in use as before. But e.g. if there was a repeatable migration with name 333_R and you deleted it (so that the "333" timestamp is not in use anymore, not even renamed), then the `repeatable-migrations.sh` script won't pick it up and might lead to inconsistent state. Just FYI, watch out when renaming the migrations :)
</blockquote></details>

Yep, this is very hackish. Thought it a better option than sticking these to some other random migration. Hopefully we don't need to do this to often. Another possible case I see might be adding more internal utils, those might make sense to be added before other repeatable stuff.
___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 31 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3K9_s9RPkfkdsopOj:-NR3PCNP4Q8s85NNTfos:b8j1z1q) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql#L31)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you've been complaining that we shouldn't use abbreviated names (like vsf, vs, jp, etc) in a similar context. Should I annoy you with the same? :P
</blockquote></details>

Here the point was to make sure we wouldn't run into PostgreSQL name length limits, and I would like to name all triggers consistently instead of abbreviating only when needed. Though, it looks like we should be fine with current triggers, longest one uneabbreviated would be `process_queued_validation_on_vehicle_schedule_frame_trigger` = 59 characters so just about within limits, so would be possible. But then, there's still tables missing from here, like `scheduled_stop_point_in_journey_pattern_ref` which would go way over limit. So, I vote for leaving these as is.

There might be some abbreviations elsewhere in aliases inside queries etc, the scope of those is more limited so they should be just fine. Also, DBeaver tends to create those automatically.
___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 147 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3L2KrCYP0ENXapZOI:-NR3U3ec3Y4dZ-c3wLx1:bre3bg2) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql#L147)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

smart! this is a good place to split the logic
</blockquote></details>

:thumbsup: would've been even uglier without this.
___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 160 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3MPfS4qhU6y_L7t4r:-NR3QwxI8nP8x_78AlUd:b-btu04u) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql#L160)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

by the way it's a valid use-case to delete an existing timetable. Though probably it's going to be implemented with a soft-delete (or store it in temporal tables...?), but it's good to keep in mind that the DELETE operations might need to be handled too. Not in scope of this PR though
</blockquote></details>

Most DELETEs don't require running current validations again, or at least they don't need info on changed rows. But true, might need to adjust these when more complicated DELETE triggers are needed.
___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 222 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3M9EmBi2B3SOU7O4O:-NR3RaZ4-riKjIqIFjez:b-l15l34) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql#L222)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

just wondering: can't you just go with "AFTER INSERT OR UPDATE" for all statement triggers instead of creating them with two separate commands?
</blockquote></details>

Unfortunately no. It's because we need `REFERENCING NEW TABLE AS new_table` here, that is, transition relation. PostgreSQL gives an error `transition tables cannot be specified for triggers with more than one event` if trying to use ´INSERT OR UPDATE` here. So multiple triggers it is..
___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 240 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3Lt_15hcWFivLn [...]

2023-03-22 07:08 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 15 of 47 files reviewed, 30 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 3 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR74lGiER20T6BiCnvb:-NR74lGiER20T6BiCnvc:bixg9te) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L3)):*
> ```XML
> import { timetablesDbConfig } from '@config';
> import { closeDbConnection, createDbConnection, DbConnection } from '@util/db';
> import * as db from '@util/db';
> ```

let's rather refrain from using `* as db` import groups
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 8 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR74iQbBEzV1MpX8QF1:-NR74iQbBEzV1MpX8QF2:b-su4i4a) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L8)):*
> ```XML
> import { insertTableData, setupDb } from '@util/setup';
> import { randomUUID } from 'crypto';
> import { defaultGenericTimetablesDbData } from 'generic/timetablesdb/datasets/defaultSetup';
> ```

let's group these imports as mentioned above
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 24 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR74qRu0ocx0h0vIZyu:-NR74qRu0ocx0h0vIZyv:bs405ar) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L24)):*
> ```XML
>   buildUpdateVehicleServiceMutation,
> } from 'generic/timetablesdb/mutations';
> import { cloneDeep, merge, pick } from 'lodash';
> ```

let's rather use default imports for lodash (lodash/cloneDeep, lodash/merge, lodash/pick)
___
*[`test/hasura/util/setup.ts` line 11 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR77p070tR9ceLSeBfd:-NR77p070tR9ceLSeBfe:b-vbul63) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/util/setup.ts#L11)):*
> ```XML
> import { Knex } from 'knex';
> 
> export const insertTableData = async <TTableName extends string>(
> ```

this shouldn't expect both a db.DbConnection (which could be both a pg pool connection or a knex transaction) and a knex.transaction as a parameter.
Rather this should only expect a db.DbConnection and create a new (sub)transaction within this function itself.
-> if it was a pg pool connection, it will be in a transaction
-> if it was already in a transaction, it doesn't hurt it it's wrapped in a (sub)transaction
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts` line 11 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7-StZ8KrpUURA4RHx:-NR7-StZ8KrpUURA4RHy:bml8m8q) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts#L11)):*
> ```XML
> import { expectNoErrorResponse } from '@util/response';
> import { queryTable, setupDb } from '@util/setup';
> import { defaultGenericTimetablesDbData } from 'generic/timetablesdb/datasets/defaultSetup';
> ```

on the UI side we've had the coding practice that we group the imports in the folder's index.ts file. E.g. here it holds no value to know that each and every dataset came from a different file, the value is only knowing that they all come from the generic dataset's defaultSetup.

...kind of like how the mutation imports are grouped below.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts` line 123 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR710W96hr99DAHBcIw:-NR710W96hr99DAHBcIx:b-3mqjrg) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts#L123)):*
> ```XML
>         expect.arrayContaining([
>           defaultDatasetRows.route123Outbound,
>           defaultDatasetRows.route123Outbound,
> ```

is there some bug here? Or maybe it's just the stupid jest matcher? How could this contain two instances of the Outbound rows? This should contain:
- one Inbound row
- one Outbound row
- one new row with the v1Sat vehicle service

Not in the scope of this PR, but this shows that we'd need a better jest array matcher that checks that all the elements exist in the expected list, but not necessarily in the same order
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts` line 135 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR72uxl1c1q6JkjwgdO:-NR72uxl1c1q6JkjwgdP:bgns3e8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts#L135)):*
> ```XML
> 
>     it('should correctly increment counts when multiple inserts and updates are required', async () => {
>       const newVehicleJourneys = {
> ```

good test. Thanks for the comments, makes it much easier to follow!
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts` line 233 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR73aeFCS_EiW65xnCB:-NR73aeFCS_EiW65xnCC:b-8657e3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts#L233)):*
> ```XML
>     it('should correctly decrement count', async () => {
>       const deleteMutation = addMutationWrapper(`
>         ${buildDeletePassingTimeMutation(
> ```

could you add a comment here that v1MonFriJourney1 is traveling along the outbound journey pattern?
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts` line 258 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR742O0DsyPbrLoGP9F:-NR742O0DsyPbrLoGP9G:b-ukykfq) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule/journey-patterns-in-vehicle-service.spec.ts#L258)):*
> ```XML
> 
>     it('should delete the row when count reaches zero', async () => {
>       const deleteMutation = addMutationWrapper(`
> ```

could you add a comment here that v1MonFriJourney1 and Journey3 both travel along the Outbound journey pattern and they are the only ones doing so?


<!-- Sent from Reviewable.io -->

2023-03-22 07:32 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 15 of 47 files reviewed, 43 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 37 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR79URe0dteZdherlSu:-NR79URe0dteZdherlSv:b-oa6lbe) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L37)):*
> ```XML
> 
>   beforeEach(async () => setupDb(dbConnection, defaultGenericTimetablesDbData));
> ```

let's rather call this cloneBaseDataset as you are technically not getting the original base dataset, but rather creating a conflicting clone with it
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 117 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR78imj9amcLsgqLLhu:-NR78imj9amcLsgqLLhv:b-igdewk) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L117)):*
> ```XML
>     dataset: ReturnType<typeof getBaseDataset>,
>   ) => {
>     // The stops need to be from same journey pattern as well, to not break other constraints.
> ```

not to break
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 143 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR78xOm7OXQxycL-wWf:-NR78xOm7OXQxycL-wWg:bus6r8q) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L143)):*
> ```XML
>     it('should fail when existing and new vehicle schedule frame have same priority, journey pattern, day of week and overlapping validity period', async () => {
>       const dataset = getBaseDataset();
>       await expect(insertDataset(dataset)).rejects.toThrow();
> ```

it would be important to also match on the error message, e.g. on the "conflicting schedules detected" text to know that the correct constraint was triggered and the rejection was not caused by something else
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 158 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7A0B9DmwP2A_8kX4C:-NR7A0BA6Ctg2hWVJnCN:brlp3ig) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L158)):*
> ```XML
>       }
> 
>       const errorMessage = error?.toString();
> ```

let's rather move this to a separate function if you wanna reuse this. But personally I think its enough if you just showed that a "conflicting scheduled detected" string was present in the result, we don't need to explicitly show that was was the full error string: we already know that from the test objects IMHO.
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 189 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7AXdhEE5M3EfU1zi9:-NR7AXdhEE5M3EfU1ziA:bw4ey4p) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L189)):*
> ```XML
>     });
> 
>     describe('priority checks', () => {
> ```

should test that:
- if there's an existing draft/staging vehicle schedule frame, one can insert an overlapping frame (with any priority, including basic/temporary/special/draft/staging) with the same attributes - without conflicts
- if there's an existing basic/temporary/special/draft/staging vehicle schedule frame, one can insert an overlapping frame with draft/staging priorities - without conflicts
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 219 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7BBLXEsdPhMvFvQuC:-NR7BBLXEsdPhMvFvQuD:bn0p247) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L219)):*
> ```XML
>         dataset.frame.validity_end = DateTime.fromISO('2023-12-31');
> 
>         await expect(insertDataset(dataset)).rejects.toThrow();
> ```

let's match on the "conflicting scheduled detected" error string
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 223 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7BOSw2mU8B8NqKtv-:-NR7BOSw2mU8B8NqKtv0:b-1usi4h) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L223)):*
> ```XML
> 
>       // No sense going through all possible combinations, that would basically be just testing PostgreSQL OVERLAPS operator.
>       // But this is an important corner case since it requires different behavior date ranges in PostgreSQL have by default:
> ```

good point, good comment!
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 233 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7BSMlA7gMUdATKHPz:-NR7BSMlA7gMUdATKHQ-:bn0p247) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L233)):*
> ```XML
>         });
> 
>         await expect(insertDataset(dataset)).rejects.toThrow();
> ```

let's match on the "conflicting scheduled detected" error string
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 252 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7Ba-B13rhmb1Z-c9W:-NR7Ba-B13rhmb1Z-c9X:bn0p247) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L252)):*
> ```XML
>         dataset.service.day_type_id = defaultDayTypeIds.WEDNESDAY;
> 
>         await expect(insertDataset(dataset)).rejects.toThrow();
> ```

let's match on the "conflicting scheduled detected" error string
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 257 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7BeNs6AKq_kGheVDo:-NR7BeNs6AKq_kGheVDp:b-522jji) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L257)):*
> ```XML
> 
>     describe('journey pattern checks', () => {
>       it('should succeed when frames do not use any common journey patters between them', async () => {
> ```

typo: patterns
___
*[`test/hasura/generic/timetablesdb/integration-test [...]

2023-03-22 07:45 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 15 of 47 files reviewed, 48 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 300 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7EfnJ6hYPnUN1_NVI:-NR7EfnJ6hYPnUN1_NVJ:b-xgudcj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L300)):*
> ```XML
>           await insertSchedulesForForeignKeyTests();
> 
>         // Move vehicle service from schedule of datasetSamePrio to schedule of datasetDifferentJourney -> creates conflict with base dataset.
> ```

it was really hard to follow what actually triggered the conflict. Could you write a sentence that with this update, we moved a vehicle service that contains a journey pattern that will conflict with the winter 2022 timetable
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 319 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7FiGRA9qX281wIbSc:-NR7FiGRA9qX281wIbSd:bobxokh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L319)):*
> ```XML
>           await insertSchedulesForForeignKeyTests();
> 
>         // Move block from schedule of datasetSamePrio to schedule of datasetDifferentJourney -> creates conflict with base dataset.
> ```

same as above: would be good to mention that we moved a block that contains a conflicting journey pattern
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 338 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7FqWb2xxCWU117lqk:-NR7FqWb2xxCWU117lql:bypapb4) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L338)):*
> ```XML
>         const updateMutation = addMutationWrapper(
>           buildUpdateVehicleJourneyMutation(
>             datasetSamePrio.journey.vehicle_journey_id,
> ```

same as above: would be good to mention that we moved a vehicle journey that contains a conflicting journey pattern
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 357 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7FzToBPRdClUKZ99k:-NR7FzToBPRdClUKZ99l:b-q6hh0n) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L357)):*
> ```XML
>         // After this datasetSamePrio has same journey as base dataset but still different priority,
>         // so there is no conflict.
>         // Same would apply to all other tables, but don't think it's worth testing all the cases.
> ```

OK :thumbsup: 
___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 397 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7GVbRBE1IXDUarm7O:-NR7GVbRBE1IXDUarm7P:bo7gv80) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L397)):*
> ```XML
>       const updateResponse = await postQuery(updateMutation);
>       expectErrorResponse('conflicting schedules detected')(updateResponse);
>     });
> ```

could you add a test here where you have two vehicle schedule frames with the same priority, journey pattern and day type, but the validity ranges don't overlap. Then should show that by updating one of the validity ranges to overlap with the other, a conflict will trigger


<!-- Sent from Reviewable.io -->

2023-03-22 09:01 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 15 of 47 files reviewed, 48 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts` line 397 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR7GVbRBE1IXDUarm7O:-NR7Y3Ez8vEEIRo_PcNf:beje5n6) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/test/hasura/generic/timetablesdb/integration-tests/data-integrity/vehicle-schedule-frame/journey-pattern-ref-unique.spec.ts#L397)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you add a test here where you have two vehicle schedule frames with the same priority, journey pattern and day type, but the validity ranges don't overlap. Then should show that by updating one of the validity ranges to overlap with the other, a conflict will trigger
</blockquote></details>

and similarly a test with two timetables that differ only by their priorities (e.g. could also make one of them a draft) and show that by modifying the priority to be the same as for the other timetable, they will conflict


<!-- Sent from Reviewable.io -->

2023-03-29 11:07 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158)* status: 15 of 47 files reviewed, 46 unresolved discussions (waiting on @pallost)

___
*[`metadata/generic/databases/default/tables/journey_pattern_journey_pattern.yaml` line 42 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3DsK_9D9hd_XtQO5T:-NRaqUpo9EQ_Vl_n3SU0:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/metadata/generic/databases/default/tables/journey_pattern_journey_pattern.yaml#L42)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Maybe `journey_pattern_vehicle_services` would be a better name for the graphql field...?

This is how it would look like in a query:
```
journey_pattern {
  journey_pattern_vehicle_services {
    vehicle_service {
      vehicle_service_id
      name_i18n
    }
  }
}
```
</blockquote></details>

:thumbsup: 
___
*[`metadata/generic/databases/timetables/tables/vehicle_service_vehicle_service.yaml` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3EdZ85e2cCQW2GQZz:-NRarPhk6UMOiyE48bMY:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/metadata/generic/databases/timetables/tables/vehicle_service_vehicle_service.yaml#L19)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

similarly as above: would `journey_patterns_in_vehicle_service` be a better name for this?
</blockquote></details>

:thumbsup: 
___
*[`migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql` line 180 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3LNciDEfxFK5Hv450:-NRaenWG13j185Elc-tm:b-yplcrp) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000000_R_after_migrate_create_validation_queue_objects/up.sql#L180)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd also add the insert trigger here for vehicle services. We might not need it right now for the current validation use-cases, but would be annoying to add this missing trigger later on.
</blockquote></details>

Not any more annoying than it is now. Not needed at the moment so won't add. If we did add those, should we also add DELETE triggers already on the same grounds? But those would require additional work since current triggers don't work with DELETE as-is.
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 18 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3Oztj5DkVT1B4_Z_4:-NRgmgPt0tC4cS4c9u19:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

note: we shouldn't check collisions for draft and staging priorities. Only for standard, temporary and special (the substitute operating day priority doesn't concern this constraint)

Let's create a constant function, like this:
```
CREATE FUNCTION internal_utils.const_priority_draft() RETURNS integer
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    AS $$SELECT 30$$;
```

then you can filter the relevant vehicle schedule frames by `WHERE priority < const_priority_draft()`
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 44 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3QaTs-4H8fniGzAoR:-NRafm4a15kt-yV1YacQ:b-9qtxfb) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L44)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

do you need this join with the journey_pattern_ref table? You already have the journey_pattern_id available from the journey_patterns_in_vehicle_service table
</blockquote></details>

Actually no, good point. Bad habit.
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 48 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3QPRU1jbvy84JoIM1:-NRahAnbE36lvAu9Q6xW:bi3ehnm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L48)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

does the = ANY() syntax work in this case?
</blockquote></details>

Nope. But actually this WHERE can be replaced with `JOIN journey_patterns_to_check USING (journey_pattern_id)`



_Code quote:_
```TSQL
journey_pattern_id IN (SELECT * FROM journey_patterns_to_check)
```
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 74 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3SFgy-iHZwrV6wAD5:-NRgmw6aEVRwHBqeOn5C:bqoield) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L74)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

...(excluding draft and staging priorities)
</blockquote></details>

Worded differently but done.
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 92 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3T5gDD7UW9nvud-9t:-NRcKCZb2SjU4ugM_qrt:bhvztvn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L92)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

imho UNIONs would be easier to read, but I guess this works too...
</blockquote></details>

Care to elaborate how you would do this cleanly with unions?

Making queries like "select vehicle_schedule_frame_id for each row in modified_vehicle_journey" for each modified_x table and UNIONing them would mean having to run similar joins in each query and be a lot more verbose. Probably would be slower as well. Or are you thinking of a different approach?

Tried this initially with nested subqueries, but that was ugly.
___
*[`migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql` line 110 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3Tx4K1iEAbnQ5DCkC:-NRais7R13fly9-ZYxxA:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000000005_R_after_migrate_add_frame_journey_pattern_unique_checks/up.sql#L110)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

well, technically this is "day of week" and not weekday :)
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000001000_R_after_migrate_execute_queued_validations/up.sql` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/158#-NR3UBNiEt634CTbNFKv:-NRanxDUAKfnZsnKhKfR:bsjxepp) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/0551539bfa9994bc1eaf276b36b3895dd1673ec4/migrations/generic/timetables/2000000001000_R_after_migrate_execute_queued_validations/up.sql#L15)):*
<details><summary><i>Previously, pal [...]

2023-03-29 11:32 UTC, merged