Add hsl timetables infra and tests
HSLdevcom/jore4-hasura pull request #186
Opened 2023-05-30 13:19 UTC by HenrikHartiala

2 commits:
**Add hsl timetables test infra**
We already have generic - network, generic - timetables and hsl - network
infra created. This commit will bring the base for hsl - timetables test infra.

Resolves https://github.com/HSLdevcom/jore4/issues/1275

**Add additional datasets and timetable version function tests**
In this commit we introduce a way to add additional datasets to the default dataset (seed).
Point of these additional datasets is that they can be reused and also they won't otherwise
affect other tests. E.g. if you need to add standard priority sunday timetable set for January
2025 for a test, you can add an additional dataset file which has all the necessary data for it.
The old way would have been to either add it to the default dataset, which would break many
existing tests, because they rely that the data is not changed.
Also add tests for 'vehicle_service.get_timetables_and_substitute_operating_days' and
'vehicle_service.get_timetable_versions_by_journey_pattern_ids'

Resolves https://github.com/HSLdevcom/jore4/issues/1295

2023-05-30 14:33 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186)* status: 0 of 25 files reviewed, 1 unresolved discussion

___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 115 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWh3hiA3Ovt_BTrKKoC:-NWh3hiA3Ovt_BTrKKoD:bo37zmw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L115)):*
> ```XML
>     expect(
>       // Sort arrays so that the order does not matter
>       sortVersionsForAssert(mappedResponse),
> ```

Open for suggestion: how to implement this (sorting part) somehow differently. Currently this was the only way I found that we do not need to match the order of the response. There is also this `expect.arrayContaining`, but first of all it does not check if the response has something extra. Also with `expect.arrayContaining` the error message is very hard to read since it has the whole array in one string.


<!-- Sent from Reviewable.io -->

2023-05-31 09:36 UTC, Leitsi requested changes
> Reviewed 18 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186)* status: 18 of 25 files reviewed, 17 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test/hasura/hsl/timetablesdb/datasets/factories.ts` line 9 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkRAqL1zNzwSDBPs5X:-NWkRAqM3l1vsTarPu7j:b-zgzx4i) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/factories.ts#L9)):*
> ```XML
> import { HslVehicleScheduleFrame } from './types';
> 
> type VehicleScheduleFrameParams = Parameters<
> ```

Should we use the full function name here, since that's whose parameters this referes to.



_Suggestion:_
```XML
type BuildVehicleScheduleFrameParams = Parameters<
```
___
*[`test/hasura/hsl/timetablesdb/datasets/factories.ts` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWh2mmvCKUNHN1HPEub:-NWh2mmvCKUNHN1HPEuc:b-20unbu) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/factories.ts#L18)):*
> ```XML
>   const { booking_label, booking_description_i18n, ...rest } = input;
>   return {
>     ...buildVehicleScheduleFrame(rest as VehicleScheduleFrame),
> ```

Looks like this works even without the typecast. Was there some specific reason for it?
___
*[`test/hasura/hsl/timetablesdb/datasets/types.ts` line 35 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkObJiBXDSfBpGseZc:-NWkObJiBXDSfBpGseZd:b-wp8x7g) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/types.ts#L35)):*
> ```XML
> ];
> 
> // TODO: Check the correct types for times
> ```

This still TODO?
___
*[`test/hasura/hsl/timetablesdb/datasets/types.ts` line 48 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkPH8q0r-NT8HTK_L7:-NWkPH8q0r-NT8HTK_L8:b-13vabe) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/types.ts#L48)):*
> ```XML
> };
> 
> export type TimetableVersion = {
> ```

The `return_value.timetable_version` table also has `validity_start` and `validity_end`, DateTime NOT NULL.
___
*[`test/hasura/hsl/timetablesdb/datasets/types.ts` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkQchg8k-vrtqdH1db:-NWkQchg8k-vrtqdH1dc:b-vxjybj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/types.ts#L50)):*
> ```XML
> export type TimetableVersion = {
>   vehicle_schedule_frame_id: UUID;
>   substitute_operating_day_by_line_type_id: UUID;
> ```

The`vehicle_schedule_frame_id` and `substitute_operating_day_by_line_type_id` fields are nullable in DB.
___
*[`test/hasura/hsl/timetablesdb/datasets/defaultSetup/substitute-operating-day-by-line-types.ts` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWh3RMF4DcamTg7kuv5:-NWh3RMG76W2JGeZL8ri:ble4q3g) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/defaultSetup/substitute-operating-day-by-line-types.ts#L11)):*
> ```XML
>     type_of_line: TypeOfLine.StoppingBusService,
>     superseded_date: DateTime.fromISO('2023-04-01'),
>     substitute_day_of_week: DayOfWeek.Friday,
> ```

Just to check: this means that 1.4.2023, which is a Saturday, will be trafficked using Friday schedules?
___
*[`test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkUDt97XhOUqCW_4aS:-NWkUDtABoGPmbWHl2km:b-2akyrw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts#L7)):*
> ```XML
> import { defaultHslTimetablesDbData } from 'hsl/timetablesdb/datasets/defaultSetup';
> 
> describe('Function service_pattern.get_distances_between_stop_points_in_journey_patterns', () => {
> ```

Forgot to change suite name here.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkS4Uc0WH8VBYw1zpG:-NWkS4Uc0WH8VBYw1zpH:b-vsxaxj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts#L22)):*
> ```XML
>       `SELECT * FROM service_calendar.substitute_operating_day_by_line_type`,
>     );
>     expect(response.rows.length).toBeGreaterThan(0);
> ```

NIT, would add empty lines here. These are quite clearly 3 different parts of the test (https://www.code4it.dev/cleancodetips/aaa-pattern-for-tests/) so makes sense to separate them.

Also, would be possible to check `substituteOperatingDayByLineTypesByName.aprilFools` here if we want.



_Suggestion:_
```XML
    await setupDb(dbConnection, defaultHslTimetablesDbData);
    
    const response = await db.singleQuery(
      dbConnection,
      `SELECT * FROM service_calendar.substitute_operating_day_by_line_type`,
    );
    
    expect(response.rows.length).toBeGreaterThan(0);
```
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 70 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkYl5bEO7KOeGj7Yww:-NWkYl5bEO7KOeGj7Ywx:b-z3et1t) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L70)):*
> ```XML
>       dbConnection,
>       `SELECT * FROM vehicle_service.get_timetable_versions_by_journey_pattern_ids('{${journeyPatternIds}}'::uuid[], '${startDate.toISODate()}'::date, '${endDate.toISODate()}'::date, '${observationDate.toISODate()}'::date)`,
>     );
> ```

Using string literals anwyay, so could maybe split this to multiple rows for clarity:



_Suggestion:_
```XML
    const response = await db.singleQuery(
      dbConnection,
      `SELECT * FROM vehicle_service.get_timetable_versions_by_journey_pattern_ids(
        '{${journeyPatternIds}}'::uuid[],
        '${startDate.toISODate()}'::date,
        '${endDate.toISODate()}'::date,
        '${observationDate.toISODate()}'::date
      )`,
    );
```
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 91 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkZ4RQAAChLOrsg5Rw:-NWkZ4RQAAChLOrsg5Rx:b-cgui9q) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L91)):*
> ```XML
>   });
> 
>   it('should only have standard priorities in effect in May', async () => {
> ```

Why is this? I'm guessing there's no special logic for May.

One point here seems to be that ascension date is not in_effect because its observation_date does not fall inside its validity range. But others still are. Could try to clarify that. Maybe something like `should only have those priorities in effect whose validity falls inside observation_date`.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 105 at r1](https://reviewable.io/rev [...]

2023-05-31 10:25 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186)* status: 18 of 25 files reviewed, 23 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 59 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWlJAjo70B6UB50TrOg:-NWlJAjo70B6UB50TrOh:b-5x0vuj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L59)):*
> ```XML
>   afterAll(() => closeDbConnection(dbConnection));
> 
>   const getTimetableVersions = async (
> ```

Some possible test cases to add:
- when called with startDate > endDate
- when observationDate is not inside start and end dates
- when called with multiple journeyPatternIds
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWlKZI9E7ayVZ1fKxMs:-NWlKZI9E7ayVZ1fKxMt:b-9bl4yw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts#L34)):*
> ```XML
> import { DateTime } from 'luxon';
> 
> const sortVersionsForAssert = (
> ```

Same as in other suite, so do replace this as well if you refactor it to a test utility.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts` line 62 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWlKBHl4mRrIKleDgh1:-NWlKBHl4mRrIKleDgh2:b-4h7nwj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts#L62)):*
> ```XML
>     journeyPatternIds: string[],
>     startDate: DateTime,
>     endDate: DateTime,
> ```

Could maybe add test for case when called with invalid range, that is, startDate > endDate.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWlJY6j79BOHw685w5B:-NWlJY6j79BOHw685w5C:bn0i4hm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts#L67)):*
> ```XML
>     const response = await db.singleQuery(
>       dbConnection,
>       `SELECT * FROM vehicle_service.get_timetables_and_substitute_operating_days('{${journeyPatternIds}}'::uuid[], '${startDate.toISODate()}'::date, '${endDate.toISODate()}'::date)`,
> ```

Same as in previous suite, maybe split to multiple rows for better readability.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts` line 73 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWlJgF9At5lGwqwtLvw:-NWlJgF9At5lGwqwtLvx:bakh5xx) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts#L73)):*
> ```XML
>   };
> 
>   it('should return rows for each vehicle_schedule_frame and substitute_operating_day excluding express bus service substitute day for 2023', async () => {
> ```

Needs clarification. Why express bus?
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts` line 90 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWlJu8q4SBHQGYLo4f4:-NWlJu8q4SBHQGYLo4f5:b-hjltxv) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get_timetables_and_substitute_operating_days/get-timetables-and-substitute-operating-days.spec.ts#L90)):*
> ```XML
>     );
> 
>     const mappedResponse = response.map((version) => ({
> ```

Maybe create a helper function for this, copypasted to each test.


<!-- Sent from Reviewable.io -->

2023-06-07 14:11 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186)* status: 13 of 30 files reviewed, 23 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/hsl/timetablesdb/datasets/factories.ts` line 9 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkRAqL1zNzwSDBPs5X:-NWqJP7C4Bbnq1pjFSdU:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/factories.ts#L9)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Should we use the full function name here, since that's whose parameters this referes to.
</blockquote></details>

:+1: 
___
*[`test/hasura/hsl/timetablesdb/datasets/factories.ts` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWh2mmvCKUNHN1HPEub:-NWqIwyBEYrFC00Tov3L:b-pw4yzh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/factories.ts#L18)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Looks like this works even without the typecast. Was there some specific reason for it?
</blockquote></details>

Hmm, this definitely had issues without the typecast at some point. But as you said it now seems to work without it, so maybe something else I did fixed it :shrug: 
___
*[`test/hasura/hsl/timetablesdb/datasets/types.ts` line 35 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkObJiBXDSfBpGseZc:-NWqrXqq5B70S1LUi5pc:b57sgcx) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/types.ts#L35)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This still TODO?
</blockquote></details>

Yes, but thanks for reminding, should be correct types now
___
*[`test/hasura/hsl/timetablesdb/datasets/types.ts` line 48 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkPH8q0r-NT8HTK_L7:-NWqtKgt9ZSFGCzsMPM_:b-osf709) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/types.ts#L48)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

The `return_value.timetable_version` table also has `validity_start` and `validity_end`, DateTime NOT NULL.
</blockquote></details>

Good one! 
___
*[`test/hasura/hsl/timetablesdb/datasets/types.ts` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkQchg8k-vrtqdH1db:-NWqtpXb-nL9vk14GOo4:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/types.ts#L50)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

The`vehicle_schedule_frame_id` and `substitute_operating_day_by_line_type_id` fields are nullable in DB.
</blockquote></details>

:+1: 
___
*[`test/hasura/hsl/timetablesdb/datasets/defaultSetup/substitute-operating-day-by-line-types.ts` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWh3RMF4DcamTg7kuv5:-NWqK2rkBZmSvh10cxtk:b-mzavww) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/datasets/defaultSetup/substitute-operating-day-by-line-types.ts#L11)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Just to check: this means that 1.4.2023, which is a Saturday, will be trafficked using Friday schedules?
</blockquote></details>

Yes, correct :heavy_check_mark: 
___
*[`test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkS4Uc0WH8VBYw1zpG:-NWva-8S9oKFu-LZ6BFz:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts#L22)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

NIT, would add empty lines here. These are quite clearly 3 different parts of the test (https://www.code4it.dev/cleancodetips/aaa-pattern-for-tests/) so makes sense to separate them.

Also, would be possible to check `substituteOperatingDayByLineTypesByName.aprilFools` here if we want.
</blockquote></details>

:+1: 
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 59 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWlJAjo70B6UB50TrOg:-NXJeb640a7BQmpEbxpB:b5d1o2t) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L59)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Some possible test cases to add:
- when called with startDate > endDate
- when observationDate is not inside start and end dates
- when called with multiple journeyPatternIds
</blockquote></details>

I added test for the "observationDate is not inside start and end dates". But actually not sure what should happen in the first case. Should we not give any results? Currently it works so that it does not matter if they are the other way around IF they are both inside a valid version.
As example:
Time range 25.6.2023 - 01.06.2023 (dates are in wrong order)
It will return 
Standard priority which is valid through the whole year of 2023
Also returns the Temporary priority that is valid through June, so 01.06.2023.

But if you choose time range that either of the dates are outside of June, it will not return that one. So:
Time range 30.06.2023 - 30.05.2023 (end date is before the validity of the temporary version (June))
Time range 01.07.2023 - 01.06.2023 (start date is after the validity of the temporary version (June))

So the question is simply that should we actually return nothing from the function in this case?

And for the 3rd suggested test, I need to add a ticket and do a separate PR at some point, because it requires some more test data. (The other journey pattern and timetables attached to it)
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 70 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkYl5bEO7KOeGj7Yww:-NXL2fUS2_EZactk-i0w:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L70)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Using string literals anwyay, so could maybe split this to multiple rows for clarity:
</blockquote></details>

:+1: 
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 91 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkZ4RQAAChLOrsg5Rw:-NWvaudO2o0KZT4v20yF:b-d8etuu) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L91)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Why is this? I'm guessing there's no special  [...]

2023-06-08 06:27 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186)* status: 13 of 30 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkUDt97XhOUqCW_4aS:-NXOW1071Z4OinS4yXI9:b-jepyyn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts#L7)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Forgot to change suite name here.
</blockquote></details>

Fixed now, but in wrong commit.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWkS4Uc0WH8VBYw1zpG:-NXOW89ACyENOIxlUoa5:b-6irslx) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/hsl-timetables-db-default-dataset-insertion.spec.ts#L22)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

This fix could've been in original commit as well though.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 59 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NWlJAjo70B6UB50TrOg:-NXOWeUC7KU42oaXspZe:b5j4pbn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/177c6da45ab00803d6c7c17f8d29ef78e52e6338/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L59)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I added test for the "observationDate is not inside start and end dates". But actually not sure what should happen in the first case. Should we not give any results? Currently it works so that it does not matter if they are the other way around IF they are both inside a valid version.
As example:
Time range 25.6.2023 - 01.06.2023 (dates are in wrong order)
It will return 
Standard priority which is valid through the whole year of 2023
Also returns the Temporary priority that is valid through June, so 01.06.2023.

But if you choose time range that either of the dates are outside of June, it will not return that one. So:
Time range 30.06.2023 - 30.05.2023 (end date is before the validity of the temporary version (June))
Time range 01.07.2023 - 01.06.2023 (start date is after the validity of the temporary version (June))

So the question is simply that should we actually return nothing from the function in this case?

And for the 3rd suggested test, I need to add a ticket and do a separate PR at some point, because it requires some more test data. (The other journey pattern and timetables attached to it)
</blockquote></details>

Feels like that start > end case is invalid parameters so should return nothing, but probably this isn't worth it to pay attention to after all.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 654 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NXOZXEa6rs7EtC4ubMb:-NXOZXEa6rs7EtC4ubMc:b-ih6nx8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/800d3aee7eb0f3bc9731fd04169160724f2c7342/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L654)):*
> ```XML
> 
>       describe('observation date is on winter timetables validity range', () => {
>         it('should have only the summer timetable version in effect', async () => {
> ```

Wrong test name here I think.



_Suggestion:_
```XML
it('should have only the winter timetable version in effect', async () => {
```
___
*[`test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts` line 657 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-NXObpzKBKVovqCTqo1T:-NXObpzKBKVovqCTqo1U:b-sqrrf4) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/800d3aee7eb0f3bc9731fd04169160724f2c7342/test/hasura/hsl/timetablesdb/integration-tests/function-get-timetable-versions-by-journey-pattern-ids/get-timetable-versions-by-journey-pattern-ids.spec.ts#L657)):*
> ```XML
>           const startDate = DateTime.fromISO('2023-05-01');
>           const endDate = DateTime.fromISO('2023-06-30');
>           const observationDate = DateTime.fromISO('2023-05-30');
> ```

Nit, this observation date could probably be a bit more clearly on the winter side.


<!-- Sent from Reviewable.io -->

2023-06-08 07:09 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/186#-:-NXOpX93-IcJnz34DHiJ:bnfp4nl)* status: 13 of 30 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-08 08:04 UTC, merged