Add substitute operating period
HSLdevcom/jore4-hasura pull request #188
Opened 2023-06-09 12:40 UTC by Perholehto

- New table `service_calendar.substitute_operating_period` to group `substitute_operating_days` 
- New view `service_calendar.substitute_operating_period_with_date_range` to get periods with date range and linetypes
- New function `service_calendar.save_operating_periods` handles saving/updating `substitute_operating_days` for `substitute_operating_periods`

2023-06-27 07:01 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @Perholehto)

___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvc5kG7jG1wh9yfwMp:-NYvc5kG7jG1wh9yfwMq:bmnsxax) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L4)):*
> ```TSQL
>     id uuid DEFAULT gen_random_uuid(),
>     period_name text UNIQUE NOT NULL,
>     is_preset BOOLEAN NOT NULL DEFAULT FALSE
> ```

Put data types lowercase as above in the previous two cases.
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvcGX-2JidQpIdSoXP:-NYvcGX-2JidQpIdSoXQ:b-rntefi) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L12)):*
> ```TSQL
>     CONSTRAINT substitute_operating_period_pkey PRIMARY KEY (id);
> 
> COMMENT ON COLUMN service_calendar.substitute_operating_period.period_name IS 'Substitute operating periods name';
> ```

period's
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvd0oT1b-BgsGD6HWB:-NYvd0oT1b-BgsGD6HWC:b-sszw3a) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L34)):*
> ```TSQL
>     SELECT
>         p.id,
>         period_name,
> ```

For style consistency, add `p.` prefix because all the other columns are equipped with table alias prefix.
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvdcPZ-AHqUFfYswTv:-NYvdcPZ-AHqUFfYswTw:byfehh8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L50)):*
> ```TSQL
> 
> CREATE
> OR REPLACE FUNCTION service_calendar.save_operating_periods(periods jsonb, removed jsonb) RETURNS SETOF service_calendar.substitute_operating_period LANGUAGE plpgsql VOLATILE AS $$ BEGIN
> ```

What are these parameters? They should be documented e.g. what is the expected contents.
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 64 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvdrE91h6E6HgThdcr:-NYvdrE91h6E6HgThdcs:bgh3rs8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L64)):*
> ```TSQL
> 
> -- Remove operating periods that have been removed
> -- Remove each day of the period
> ```

You should indent all statements inside the SQL function since it visually looks like this `DELETE` statement is not part of the function.


<!-- Sent from Reviewable.io -->

2023-06-27 12:53 UTC, HenrikHartiala requested changes
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: all files reviewed, 11 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwg97p9fXdGOlrhHIo):*
You had nice bullet points to sum the commit in the PR description,  you could add them also in the commit body here :+1: 

Also: is there a ticket about this hasura side? If there is, then you could/should add the "Resolves HSLdevcom/jore4#foobar"
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/down.sql` line 8 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwhErlD4zS552ddouC:-NYwhErlD4zS552ddouD:b3jxbl0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/down.sql#L8)):*
> ```TSQL
>     ONLY service_calendar.substitute_operating_day_by_line_type DROP COLUMN substitute_operating_period_id;
> 
> DROP TABLE service_calendar.substitute_operating_period;
> ```

No newline at the end of file.
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwokOyCUS-yaxLcC6o:-NYwokOyCUS-yaxLcC6p:bpwertt) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L2)):*
> ```TSQL
> CREATE TABLE service_calendar.substitute_operating_period (
>     id uuid DEFAULT gen_random_uuid(),
> ```

I think this `id` should be named substitute_operating_period_id to be consistent with other table id naming. If I remember the initial reason why we name these like that and not just "id" was so that we can use for example join -clauses with the USING -clause.
```
JOIN vehicle_service.vehicle_service vs USING (vehicle_schedule_frame_id)
```
So this way if the id field matches the other table's foreign key field name, this is possible.
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 42 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwqYyu4e1tZ9OtJC3K:-NYwqYyu4e1tZ9OtJC3L:bms39y8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L42)):*
> ```TSQL
>         MAX(d.end_time) AS end_time
>     FROM
>         service_calendar.substitute_operating_period p
> ```

NIT,  I think the table names have been shortened by using all the first letters of the table.

This also will help the readability in the long run, if the same tables are always shortened the same way.



_Suggestion:_
```TSQL
        service_calendar.substitute_operating_period sop
```
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwpvo5C6XYoCHzRr5Z:-NYwpvo5C6XYoCHzRr5_:b-w3ds4n) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L43)):*
> ```TSQL
>     FROM
>         service_calendar.substitute_operating_period p
>         INNER JOIN service_calendar.substitute_operating_day_by_line_type d ON p.id = d.substitute_operating_period_id
> ```

As mentioned in an earlier comment, if the `id` is named `substitute_operating_period_id`, you can simplify this clause:
Also here the same comment about the table name shorten. `d` kind of doesn't ring any bells for me, but if this was `sodblt`, I would immediately recognise this :+1: 



_Suggestion:_
```TSQL
        INNER JOIN service_calendar.substitute_operating_day_by_line_type sodblt USING(substitute_operating_period_id)
```
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 115 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwjsC4BHL4I-yOnZs2:-NYwjsC4BHL4I-yOnZs3:b48iw3k) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L115)):*
> ```TSQL
> WHERE
>     EXISTS(
>         SELECT
> ```

Im definitely not the best to judge the intendations and linebreaks on SLQ files, but this looks a bit different style than used in other SQL files. So this suggestion might be wrong, but in other files I think the linebreaks and intendations are closer to this?



_Suggestion:_
```TSQL
DELETE FROM service_calendar.substitute_operating_day_by_line_type sodblt
WHERE EXISTS(
  SELECT 1
  FROM operating_periods
  WHERE sodblt.substitute_operating_period_id = operating_periods.id
    );
```
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 178 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwhJJz2o7jV9RNYgqi:-NYwhJJz2o7jV9RNYgqj:b3jxbl0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L178)):*
> ```TSQL
> END;
> 
> $$;
> ```

No newline at the end of file.


<!-- Sent from Reviewable.io -->

2023-06-27 12:58 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: all files reviewed, 12 unresolved discussions (waiting on @Perholehto)

___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 63 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwvMaI0cXrQi8pkTTT:-NYwvMaI0cXrQi8pkTTU:b-6e9iau) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L63)):*
> ```TSQL
>     ) ON COMMIT DROP;
> 
> -- Remove operating periods that have been removed
> ```

NIT, maybe there is another way of saying this 



_Suggestion:_
```TSQL
-- Remove given (removed jsonb) operating periods.
```


<!-- Sent from Reviewable.io -->

2023-06-27 13:10 UTC, HenrikHartiala requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: all files reviewed, 12 unresolved discussions (waiting on @Perholehto)

___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwokOyCUS-yaxLcC6o:-NYwy5_-5v5LiNvjSCw4:b-rndbxt) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L2)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this `id` should be named substitute_operating_period_id to be consistent with other table id naming. If I remember the initial reason why we name these like that and not just "id" was so that we can use for example join -clauses with the USING -clause.
```
JOIN vehicle_service.vehicle_service vs USING (vehicle_schedule_frame_id)
```
So this way if the id field matches the other table's foreign key field name, this is possible.
</blockquote></details>

This also might help readability in UI side, but the downside is that the keyField for apollo needs to be manually added (but this is on the UI side)


<!-- Sent from Reviewable.io -->

2023-06-28 08:17 UTC, jarkkoka requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: all files reviewed, 12 unresolved discussions (waiting on @HenrikHartiala and @Perholehto)

___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwokOyCUS-yaxLcC6o:-NZ03ewQ-f0eKMy-jRd3:b-ptoko4) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L2)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This also might help readability in UI side, but the downside is that the keyField for apollo needs to be manually added (but this is on the UI side)
</blockquote></details>

That's right. We have an established naming convention for (primary key) ID columns where the name of the table is included in the column name. We should stick to these conventions because otherwise code becomes messy.


<!-- Sent from Reviewable.io -->

2023-07-12 07:24 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: 4 of 15 files reviewed, 12 unresolved discussions (waiting on @HenrikHartiala and @jarkkoka)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwg97p9fXdGOlrhHIo):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You had nice bullet points to sum the commit in the PR description,  you could add them also in the commit body here :+1: 

Also: is there a ticket about this hasura side? If there is, then you could/should add the "Resolves HSLdevcom/jore4#foobar"
</blockquote></details>

Added description, but there is no ticket for Hasura, will link this PR to ticket
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/down.sql` line 8 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwhErlD4zS552ddouC:-N_7xqyD8EKIZMfjDin-:b9p6kj3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/down.sql#L8)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

No newline at the end of file.
</blockquote></details>

Newline added
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwokOyCUS-yaxLcC6o:-N_7y0df733j6p0q2_9P:bo9wdid) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L2)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

That's right. We have an established naming convention for (primary key) ID columns where the name of the table is included in the column name. We should stick to these conventions because otherwise code becomes messy.
</blockquote></details>

Id changed it to be in line with other ids. I understand that it's a convention but I slightly disagree with this.
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvc5kG7jG1wh9yfwMp:-N_7yUD15TpAZDdFv3oR:b-q615k8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Put data types lowercase as above in the previous two cases.
</blockquote></details>

Changed data types to lowercase
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvcGX-2JidQpIdSoXP:-N_7ydg2E2zW8EgDmZ26:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

period's
</blockquote></details>

Done.
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvd0oT1b-BgsGD6HWB:-N_7ylVdEvmO7UtUHUcF:b-23k4w3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L34)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

For style consistency, add `p.` prefix because all the other columns are equipped with table alias prefix.
</blockquote></details>

Function removed
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 42 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwqYyu4e1tZ9OtJC3K:-N_7ysJQ6PWfvJ8NvuaK:b-23k4w3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L42)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT,  I think the table names have been shortened by using all the first letters of the table.

This also will help the readability in the long run, if the same tables are always shortened the same way.

</blockquote></details>

Function removed
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwpvo5C6XYoCHzRr5Z:-N_7yrrW0h5iUEKNm2EE:b-23k4w3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L43)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

As mentioned in an earlier comment, if the `id` is named `substitute_operating_period_id`, you can simplify this clause:
Also here the same comment about the table name shorten. `d` kind of doesn't ring any bells for me, but if this was `sodblt`, I would immediately recognise this :+1: 
</blockquote></details>

Function removed
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvdcPZ-AHqUFfYswTv:-N_7yo5g3M6zKg7I7Qqy:b-23k4w3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L50)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

What are these parameters? They should be documented e.g. what is the expected contents.
</blockquote></details>

Function removed
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 63 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwvMaI0cXrQi8pkTTT:-N_7yscD-xuH5fk6Rpp6:b-23k4w3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L63)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, maybe there is another way of saying this 
</blockquote></details>

Function removed
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 64 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYvdrE91h6E6HgThdcr:-N_7yoNT8ZymgxC__j94:b-23k4w3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L64)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You should indent all statements inside the SQL function since it visually looks like this `DELETE` statement is not part of the function.
</blockquote></details>

Function removed
___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 115 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwjsC4BHL4I-yOnZs2:-N_7yrPB4IdxHLhXz-XT:b-23k4w3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L115)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Im definitely not the best to judge the intendations and linebreaks on SLQ files, but this looks a bit different style than used in other SQL files. So this su [...]

2023-07-12 07:40 UTC, HenrikHartiala requested changes
> Reviewed 10 of 11 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: all files reviewed, 7 unresolved discussions (waiting on @jarkkoka and @Perholehto)

___
*[`test/hasura/hsl/timetablesdb/datasets/types.ts` line 36 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-N_7wcSd5VmvFYw2OQwV:-N_7wcSd5VmvFYw2OQwW:b-fqlzif) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/20c2737e3f553b23bb3a9983c69d27507f349a3e/test/hasura/hsl/timetablesdb/datasets/types.ts#L36)):*
> ```XML
> ];
> export const SubstituteOperatingPeriodProps: Property[] = [
>   'id,',
> ```

This seems to be still 'id'



_Suggestion:_
```XML
  'substitute_operating_period_id,',
```
___
*[`test/hasura/hsl/timetablesdb/datasets/defaultSetup/substitute_operating_period.ts` line 7 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-N_81E-bCb-lQbZAhK4p:-N_81E-bCb-lQbZAhK4q:b-i39b4i) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85d4a3577900fa33c7f4b9569c9ea454d169c1e0/test/hasura/hsl/timetablesdb/datasets/defaultSetup/substitute_operating_period.ts#L7)):*
> ```XML
>     substitute_operating_period_id: '0967a31a-8304-4440-9a8e-18bb67b28166',
>     is_preset: false,
>     period_name: 'Default korvausjakso',
> ```

NIT, english & finnish mixed. Also what does the "default" mean here?


<!-- Sent from Reviewable.io -->

2023-07-31 12:51 UTC, HenrikHartiala reviewed
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: all files reviewed, 5 unresolved discussions (waiting on @jarkkoka)

___
*[`test/hasura/hsl/timetablesdb/datasets/defaultSetup/substitute_operating_period.ts` line 7 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-N_81E-bCb-lQbZAhK4p:-Nag-5LQDMCJf_j0tKO5:b6x532s) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85d4a3577900fa33c7f4b9569c9ea454d169c1e0/test/hasura/hsl/timetablesdb/datasets/defaultSetup/substitute_operating_period.ts#L7)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Changed this one period name and others to have more describing naming
</blockquote></details>

Thanks :+1: 


<!-- Sent from Reviewable.io -->

2023-08-01 06:53 UTC, jarkkoka reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Perholehto)

___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwokOyCUS-yaxLcC6o:-Nag1Cdk1NhaSFym1S7r:b-4c4y4e) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L2)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Id changed it to be in line with other ids. I understand that it's a convention but I slightly disagree with this.
</blockquote></details>

It would be quite a mess if we mixed different conventions. When we have established a convention it is better to stick with it. IMO that is a (much) stronger argument than personal preferences with regard to naming columns.

However, what is still missing here is `COMMENT ON TABLE` that describes the purpose of the new table introduced here.


<!-- Sent from Reviewable.io -->

2023-08-07 10:56 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: 16 of 18 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NYwokOyCUS-yaxLcC6o:-Nak-ho914CbqSafSlRh:b-odhooi) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/48436348aac10d360a4268938c29abe8aa719359/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L2)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It would be quite a mess if we mixed different conventions. When we have established a convention it is better to stick with it. IMO that is a (much) stronger argument than personal preferences with regard to naming columns.

However, what is still missing here is `COMMENT ON TABLE` that describes the purpose of the new table introduced here.
</blockquote></details>

Added comment for table

Of topic: I'm not saying that my personal preference should be prioritized over an established convention. Just asking stupid questions and trying to find all the conventions... I will follow this convention as a developer in a team should do. It doesn't mean that I need to fully agree with this convention to use it and in future projects I will still suggest using different naming convention...


<!-- Sent from Reviewable.io -->

2023-08-09 13:08 UTC, jarkkoka requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: all files reviewed, 1 unresolved discussion (waiting on @Perholehto)

___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 18 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NbPP8xWE2zwqrTruE5a:-NbPP8xWE2zwqrTruE5b:b-1yacqe) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e9d54e54730256272afb24c886562fb1e0f6526f/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L18)):*
> ```TSQL
> 
> ALTER TABLE ONLY service_calendar.substitute_operating_day_by_line_type
> ADD CONSTRAINT substitute_operating_day_by_line_type_substitute_operating_period_fkey FOREIGN KEY (substitute_operating_period_id) REFERENCES service_calendar.substitute_operating_period(substitute_operating_period_id) ON DELETE CASCADE;
> ```

This identifier will be truncated because it exceeds 63 characters. IMO, you should name it so that it doesn't exceed 63 characters.


<!-- Sent from Reviewable.io -->

2023-08-10 06:33 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql` line 18 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-NbPP8xWE2zwqrTruE5a:-NbT7w6ODldpdhWFUpo7:bxxstu3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e9d54e54730256272afb24c886562fb1e0f6526f/migrations/hsl/timetables/1683624912748_create_substitute_operating_period/up.sql#L18)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This identifier will be truncated because it exceeds 63 characters. IMO, you should name it so that it doesn't exceed 63 characters.
</blockquote></details>

Good catch!

Renamed `constraint` and also `index` from below that exceeded  63 characters.


<!-- Sent from Reviewable.io -->

2023-08-10 06:40 UTC, jarkkoka approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-:-NbTA63Y2L04_HCtG2wC:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Perholehto)



<!-- Sent from Reviewable.io -->

2023-08-10 09:25 UTC, HenrikHartiala approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/188#-:-NbTkwfT05id7Q-R8fyQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Perholehto)



<!-- Sent from Reviewable.io -->

2023-08-10 09:59 UTC, merged