Pass secrets as secret files to docker image
HSLdevcom/jore4-hasura pull request #2
Opened 2021-05-17 09:27 UTC by tk-vincit

2021-05-17 11:11 UTC, haphut requested changes
Nice! Quick work.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-:-M_u0Lkr5NDlzQz52Zwc:b-v1rms7)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_u-sgU33olwm7zndFd:-M_u-sgV7ao2M34CZ9Dl:bnlr87u) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8544cd7ae06e9583f8dd8147900fdc3e6a1594bf/Dockerfile#L4)):*
> ```Dockerfile
> ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE="anonymous"
> COPY ./hasura/migrations /hasura-migrations
> COPY ./hasura/metadata /hasura-metadata
> ```

Copy  entrypoint as well.
___
*[docker-entrypoint.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_u-xyj118otsSoc7dT:-M_u-xyj118otsSoc7dU:b-62btme) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8544cd7ae06e9583f8dd8147900fdc3e6a1594bf/docker-entrypoint.sh#L2)):*
> ```Shell
> #!/bin/sh
> HASURA_GRAPHQL_DATABASE_URL="$(cat /secrets/HASURA_GRAPHQL_DATABASE_URL)" \
> ```

Piece this together from the separate secrets in Azure.
___
*[docker-entrypoint.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_u0HqL72h-EgZ-0hvG:-M_u0HqL72h-EgZ-0hvH:body3r3) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8544cd7ae06e9583f8dd8147900fdc3e6a1594bf/docker-entrypoint.sh#L5)):*
> ```Shell
>   HASURA_GRAPHQL_ADMIN_SECRET="$(cat /secrets/HASURA_GRAPHQL_ADMIN_SECRET)" \
>   exec /bin/docker-entrypoint.sh
> ```

Extra newline


<!-- Sent from Reviewable.io -->

2021-05-17 11:30 UTC, haphut requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_u-sgU33olwm7zndFd:-M_u4U9g8w8rgIIJhcEA:bo9d927) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8544cd7ae06e9583f8dd8147900fdc3e6a1594bf/Dockerfile#L4)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Copy  entrypoint as well.
</blockquote></details>

Actually, maybe it's clener to `WORKDIR /app` and then `COPY ./docker-entrypoint.sh ./`. That way we explicitly specify where our entrypoint goes in the image. And we could use `/app/docker-entrypoint.sh` below.


<!-- Sent from Reviewable.io -->

2021-05-17 13:08 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @haphut and @pallost)

___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_u-sgU33olwm7zndFd:-M_uHtcF4A_C4tBWUdHP:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8544cd7ae06e9583f8dd8147900fdc3e6a1594bf/Dockerfile#L4)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Actually, maybe it's clener to `WORKDIR /app` and then `COPY ./docker-entrypoint.sh ./`. That way we explicitly specify where our entrypoint goes in the image. And we could use `/app/docker-entrypoint.sh` below.
</blockquote></details>

Done.
___
*[docker-entrypoint.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_u-xyj118otsSoc7dT:-M_uRFR63A-0gnM_c6Hh:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8544cd7ae06e9583f8dd8147900fdc3e6a1594bf/docker-entrypoint.sh#L2)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Piece this together from the separate secrets in Azure.
</blockquote></details>

Done.
___
*[docker-entrypoint.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_u0HqL72h-EgZ-0hvG:-M_uIdbU2su_XgDpZGlP:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/8544cd7ae06e9583f8dd8147900fdc3e6a1594bf/docker-entrypoint.sh#L5)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Extra newline
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-18 10:32 UTC, lassemaatta requested changes
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

___
*[README.md, line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z14q1-0oeqTbc_5qo:-M_z14q1-0oeqTbc_5qp:baeejzd) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/README.md#L9)):*
> ```Markdown
> Generate local secrets on first start:
> ```sh
> chmod u+x ./setup-local-env.sh
> ```

Is there some security reason why the execute bit cannot be committed into git?
___
*[setup-local-env.sh, line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z08Ow17EQ6Y_ifha3:-M_z08Ox8rkT6AnAXSOL:bmicif7) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L2)):*
> ```Shell
> #!/bin/sh
> ```

Add something like `set -euo pipefail` here.
___
*[setup-local-env.sh, line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z0KGj6XWJCXz4KsuJ:-M_z0KGj6XWJCXz4KsuK:bxxw63b) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L15)):*
> ```
> $HASURA_ADMIN_SEECRET
> ```

`HASURA_ADMIN_SEECRET` -> `HASURA_ADMIN_SECRET`
___
*[setup-local-env.sh, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z0jkw0pI-VV-0cHn0:-M_z0jkw0pI-VV-0cHn1:b-sv9euz) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L19)):*
> ```Shell
>     random_filename=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1);
>     echo ${random_filename} > ./secrets/hsl-jore4-hasura-graphql-admin-secret
> fi
> ```

Might be a good idea to add a comment explaining why the hasura admin secret cannot be a constant. (And if it can, then why can't we just commit the secrets instead of generating them?).


<!-- Sent from Reviewable.io -->

2021-05-18 10:36 UTC, lassemaatta requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

___
*[docker-compose.yml, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z1gjk60EyTd7V4wQx:-M_z1gjk60EyTd7V4wQy:bhc80la) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/docker-compose.yml#L13)):*
> ```YAML
>           - postgis
>     environment:
>       POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
> ```

Should we also use the secrets here, so that it's actually guaranteed that they work? That is, the configuration/secrets for both this `postgis` service and `hasura` must be identical: in the current state I cannot just change `hsl-jore4-public-db-database` to whatever I want because it only affects  the`hasura` service.


<!-- Sent from Reviewable.io -->

2021-05-18 10:38 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 2 of 7 files reviewed, 8 unresolved discussions (waiting on @haphut, @lassemaatta, @pallost, and @tk-vincit)

___
*[README.md, line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z14q1-0oeqTbc_5qo:-M_z28jCEmSKFq54yT1r:b77gpug) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/README.md#L9)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Is there some security reason why the execute bit cannot be committed into git?
</blockquote></details>

I guess not. TIL :exploding_head: 
___
*[setup-local-env.sh, line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z08Ow17EQ6Y_ifha3:-M_z28LUAmot0oZ0yspg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Add something like `set -euo pipefail` here.
</blockquote></details>

Done.
___
*[setup-local-env.sh, line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z0KGj6XWJCXz4KsuJ:-M_z27vG7MahUVD_TNkR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L15)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> $HASURA_ADMIN_SEECRET
> ```

`HASURA_ADMIN_SEECRET` -> `HASURA_ADMIN_SECRET`
</blockquote></details>

Done.
___
*[setup-local-env.sh, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z0jkw0pI-VV-0cHn0:-M_z2Obp1Bz3S-2hqXay:bc54qfz) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L19)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Might be a good idea to add a comment explaining why the hasura admin secret cannot be a constant. (And if it can, then why can't we just commit the secrets instead of generating them?).
</blockquote></details>

Well, that is a good question. I think it could be constant too... Does @haphut have opinion about this?


<!-- Sent from Reviewable.io -->

2021-05-18 11:00 UTC, lassemaatta reviewed
> Reviewed 4 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: all files reviewed, 5 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-05-19 09:05 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: all files reviewed, 11 unresolved discussions (waiting on @haphut, @lassemaatta, and @tk-vincit)

___
*[docker-compose.yml, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z1gjk60EyTd7V4wQx:-Ma2qmpI7GPDN07vCSjQ:baij8aw) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/docker-compose.yml#L13)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Should we also use the secrets here, so that it's actually guaranteed that they work? That is, the configuration/secrets for both this `postgis` service and `hasura` must be identical: in the current state I cannot just change `hsl-jore4-public-db-database` to whatever I want because it only affects  the`hasura` service.
</blockquote></details>

we do not need to use secrets for the postgis database as it comes as a separate service in Azure. When testing locally, the developer may decide whether s/he wants to use secrets or env variables
___
*[docker-compose.yml, line 53 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2qDbh42JOPtJCvP2m:-Ma2qDbi1Kh1kb8ioDeo:b-igty26) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/docker-compose.yml#L53)):*
> ```YAML
> 
> secrets:
>   hsl-jore4-hasura-username:
> ```

rather use generic names for secrets (like `db-username`, `db-password`, etc) as there will be a renaming step when binding to key-vault secrets
___
*[docker-entrypoint.sh, line 1 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2rBjy0tdEs2b2JyjF:-Ma2rBjy0tdEs2b2JyjG:b-nfu8f1) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/docker-entrypoint.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

should rather call this e.g. `jore4-hasura-docker-entrypoint.sh` not to confuse it with the original `/bin/docker-entrypoint.sh` file
___
*[docker-entrypoint.sh, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2pVMS8GK2CtBTwhvz:-Ma2pVMS8GK2CtBTwhw-:bcxvi45) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/docker-entrypoint.sh#L7)):*
> ```Shell
> HASURA_GRAPHQL_ADMIN_SECRET="$(cat /secrets/hsl-jore4-hasura-password)" \
> # format: postgres://<user>:<password>@<host>:<port>/<db-name>
>   HASURA_GRAPHQL_DATABASE_URL="postgres://$(cat /secrets/hsl-jore4-hasura-username):$(cat /secrets/hsl-jore4-hasura-password)@$(cat /secrets/hsl-jore4-public-db-hostname):5432/$(cat /secrets/hsl-jore4-public-db-database)" \
> ```

the folder path has to be configurable (`SECRET_STORE_BASE_PATH`) and the variable names have to be transparent for hasura (it should not know what the name of the secret is in the key-vault as it might change). We anyway do a renaming while mapping these secrets to the container, so it's easiest to just use e.g. `db-username`, `db-password`, etc. Basically, like this: :)

```
              SECRET_STORE_BASE_PATH="${SECRET_STORE_BASE_PATH:-./run/secrets}"
              DB_USERNAME="$(cat ${SECRET_STORE_BASE_PATH}/db-username)"
              DB_PASSWORD="$(cat ${SECRET_STORE_BASE_PATH}/db-password)"
              DB_HOSTNAME="$(cat ${SECRET_STORE_BASE_PATH}/db-hostname)"
              DB_DATABASE="$(cat ${SECRET_STORE_BASE_PATH}/db-database)"
              HASURA_GRAPHQL_DATABASE_URL="postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}:5432/${DB_DATABASE}"
```
___
*[README.md, line 159 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2qdJoBBrUkWSic11V:-Ma2qdJoBBrUkWSic11W:bi9f0qm) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/README.md#L159)):*
> ```Markdown
> 
> Currently following files are needed in production:
> | Secret file |
> ```

db-username, db-password, db-hostname, db-database
___
*[setup-local-env.sh, line 10 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2rsjA9ZTERIWW4MZB:-Ma2rsjB19O8a8BWknXE:bi5f31w) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/setup-local-env.sh#L10)):*
> ```Shell
> SECRETS_DIRECTORY="./secrets"
> HASURA_ADMIN_SECRET="$SECRETS_DIRECTORY"/"hsl-jore4-hasura-graphql-admin-secret"
> HASURA_USERNAME="$SECRETS_DIRECTORY"/"hsl-jore4-hasura-username"
> ```

this is rather "DB_USERNAME" and "DB_PASSWORD", isn't it...?
___
*[setup-local-env.sh, line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2MLMU4L6e6pjeMUOj:-Ma2MLMU4L6e6pjeMUOk:bf32si9) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/setup-local-env.sh#L15)):*
> ```Shell
> DB_DATABASE="$SECRETS_DIRECTORY"/"hsl-jore4-public-db-database"
> 
> [ -d "$SECRETS_DIRECTORY" ] || mkdir "$SECRETS_DIRECTORY"
> ```

`mkdir -p`


<!-- Sent from Reviewable.io -->

2021-05-19 10:12 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: all files reviewed, 11 unresolved discussions (waiting on @haphut, @lassemaatta, and @pallost)

___
*[docker-compose.yml, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z1gjk60EyTd7V4wQx:-Ma326GLE_UfIMtvsHXu:b2f6rlj) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/docker-compose.yml#L13)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we do not need to use secrets for the postgis database as it comes as a separate service in Azure. When testing locally, the developer may decide whether s/he wants to use secrets or env variables
</blockquote></details>

So do we want to do anything with this or no?
Probably it's technically possible to create also postgres password file in `setup-local-env.sh` and use it in docker-compose...
https://www.postgresql.org/docs/current/libpq-pgpass.html
___
*[docker-compose.yml, line 53 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2qDbh42JOPtJCvP2m:-Ma2zFukAZ7q_JRKJbYU:b-ir8az1) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/docker-compose.yml#L53)):*
> ng step when binding to key-vault secrets
As you wish.
___
*[docker-entrypoint.sh, line 1 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2rBjy0tdEs2b2JyjF:-Ma2zLkP5BppCcWxfJRa:bc622it) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/docker-entrypoint.sh#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should rather call this e.g. `jore4-hasura-docker-entrypoint.sh` not to confuse it with the original `/bin/docker-entrypoint.sh` file
</blockquote></details>

Not sure if this makes sense. This filename is already unique within contents of this repository.
___
*[docker-entrypoint.sh, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2pVMS8GK2CtBTwhvz:-Ma30Ixf3P9JOz2eSzRz:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/docker-entrypoint.sh#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the folder path has to be configurable (`SECRET_STORE_BASE_PATH`) and the variable names have to be transparent for hasura (it should not know what the name of the secret is in the key-vault as it might change). We anyway do a renaming while mapping these secrets to the container, so it's easiest to just use e.g. `db-username`, `db-password`, etc. Basically, like this: :)

```
              SECRET_STORE_BASE_PATH="${SECRET_STORE_BASE_PATH:-./run/secrets}"
              DB_USERNAME="$(cat ${SECRET_STORE_BASE_PATH}/db-username)"
              DB_PASSWORD="$(cat ${SECRET_STORE_BASE_PATH}/db-password)"
              DB_HOSTNAME="$(cat ${SECRET_STORE_BASE_PATH}/db-hostname)"
              DB_DATABASE="$(cat ${SECRET_STORE_BASE_PATH}/db-database)"
              HASURA_GRAPHQL_DATABASE_URL="postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}:5432/${DB_DATABASE}"
```
</blockquote></details>

Done.
___
*[README.md, line 159 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2qdJoBBrUkWSic11V:-Ma35UG0Csrcq9XuOo7I:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/README.md#L159)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

db-username, db-password, db-hostname, db-database
</blockquote></details>

Done.
___
*[setup-local-env.sh, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z0jkw0pI-VV-0cHn0:-Ma35WP49dyiq5b0sxFu:bkhjmo2) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well, that is a good question. I think it could be constant too... Does @haphut have opinion about this?
</blockquote></details>

I guess we don't need this for now so removed this.
___
*[setup-local-env.sh, line 10 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2rsjA9ZTERIWW4MZB:-Ma35bim7VpMF7AzMmmE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/setup-local-env.sh#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is rather "DB_USERNAME" and "DB_PASSWORD", isn't it...?
</blockquote></details>

Done.
___
*[setup-local-env.sh, line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2MLMU4L6e6pjeMUOj:-Ma35_oh0LzStctKoNEI:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/setup-local-env.sh#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`mkdir -p`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-19 10:23 UTC, lassemaatta requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 2 of 7 files reviewed, 10 unresolved discussions (waiting on @haphut, @lassemaatta, and @pallost)

___
*[docker-compose.yml, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z1gjk60EyTd7V4wQx:-Ma38aGI8lL1d_mUEFBZ:bsn3wpr) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/docker-compose.yml#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

So do we want to do anything with this or no?
Probably it's technically possible to create also postgres password file in `setup-local-env.sh` and use it in docker-compose...
https://www.postgresql.org/docs/current/libpq-pgpass.html
</blockquote></details>

As discussed in slack: we can probably leave this as-is. It would be nice to provide the secrets to postgres, but it's not easy.
___
*[setup-local-env.sh, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z0jkw0pI-VV-0cHn0:-Ma38Hrw2sZB6SoaT5Yq:bdjhl28) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I guess we don't need this for now so removed this.
</blockquote></details>

If these are all constants -> why not just commit the secret files into git? No need to generate anything or to run this script.


<!-- Sent from Reviewable.io -->

2021-05-19 10:24 UTC, lassemaatta reviewed
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: all files reviewed, 10 unresolved discussions (waiting on @haphut and @pallost)



<!-- Sent from Reviewable.io -->

2021-05-19 10:27 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: all files reviewed, 5 unresolved discussions (waiting on @haphut and @tk-vincit)

___
*[docker-compose.yml, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z1gjk60EyTd7V4wQx:-Ma38Wz6Cy0681UKxHUL:blk4t93) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/docker-compose.yml#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

So do we want to do anything with this or no?
Probably it's technically possible to create also postgres password file in `setup-local-env.sh` and use it in docker-compose...
https://www.postgresql.org/docs/current/libpq-pgpass.html
</blockquote></details>

In my opinion it's nice to have but not sure if it's worth the effort (to set up the postgresql docker container using secrets)
___
*[docker-entrypoint.sh, line 1 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma2rBjy0tdEs2b2JyjF:-Ma38nUX3Y69gipQ1i3d:bxgvfln) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/35be7f210ab0baa9951812d052ca330a2112d57b/docker-entrypoint.sh#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if this makes sense. This filename is already unique within contents of this repository.
</blockquote></details>

yes, but you are calling the other `docker-entrypoint.sh` from within this entrypoint script. If you wish to keep the name, it's okay, but then you should at least comment to the `exec docker-entrypoint.sh` line that you are calling forward to the "original" docker-entrypoint that came with the parent docker image


<!-- Sent from Reviewable.io -->

2021-05-19 12:07 UTC, pallost approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 2 of 12 files reviewed, 5 unresolved discussions (waiting on @haphut, @lassemaatta, and @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-05-19 13:08 UTC, haphut requested changes
Please add "Fixes HSLdevcom/jore4#323" into a separate line in your PR description and check the issue page for a reference to the issue. That way the issue and the board automation will pick up on it.

> Reviewed 2 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-:-Ma3h1_mCOxl_35eW22Y:b-nk5loh)* status: 4 of 12 files reviewed, 3 unresolved discussions (waiting on @lassemaatta and @tk-vincit)

___
*[docker-entrypoint.sh, line 10 at r5](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma3g8_3-GoRC_ZED-kJ:-Ma3g8_3-GoRC_ZED-kK:b3y316x) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3d72f1832d7d71a3a633fe8fb84ae8bf92f834b8/docker-entrypoint.sh#L10)):*
> ```Shell
> DB_PASSWORD="$(cat ${SECRET_STORE_BASE_PATH}/db-password)"
> DB_HOSTNAME="$(cat ${SECRET_STORE_BASE_PATH}/db-hostname)"
> DB_NAME="$(cat ${SECRET_STORE_BASE_PATH}/db-name)"
> ```

In this case it's not a problem but my `shellcheck` often complains to me when I try to use variables without quoting because of the possible spaces within. Though here we know there are no spaces in `run/secrets`. Here I would expect `DB_NAME="$(cat "${SECRET_STORE_BASE_PATH}/db-name")"`.

Up to you. I think this is fine as is.
___
*[README.md, line 7 at r5](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-Ma3gty31U3yDFm4-xlN:-Ma3gty31U3yDFm4-xlO:b-9yr1l5) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3d72f1832d7d71a3a633fe8fb84ae8bf92f834b8/README.md#L7)):*
> ```Markdown
> ## Quickstart
> ```

What's this extra line? Prettier would catch it but I guess it's not on in this repo.
___
*[setup-local-env.sh, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z0jkw0pI-VV-0cHn0:-Ma3iGPyB_XLkRGSw0rk:b2bep53) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L19)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

If these are all constants -> why not just commit the secret files into git? No need to generate anything or to run this script.
</blockquote></details>

Hmm... I'm not sure. I feel uncomfortable having secrets committed even for development use. Though a feeling ain't much.

The current docker-compose.yml exposes port 8080 to the world, so not just for localhost. With committed secrets it becomes git noise to change them and thus we probably end up hosting services with known passwords during development.


<!-- Sent from Reviewable.io -->

2021-05-19 14:15 UTC, lassemaatta requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 4 of 12 files reviewed, 3 unresolved discussions (waiting on @haphut, @lassemaatta, and @tk-vincit)

___
*[setup-local-env.sh, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-M_z0jkw0pI-VV-0cHn0:-Ma3xRIr9nd0AHk4TKFf:bz5hm0p) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a215441af82565ef88189f9f5b9889fe24a507d6/setup-local-env.sh#L19)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Hmm... I'm not sure. I feel uncomfortable having secrets committed even for development use. Though a feeling ain't much.

The current docker-compose.yml exposes port 8080 to the world, so not just for localhost. With committed secrets it becomes git noise to change them and thus we probably end up hosting services with known passwords during development.
</blockquote></details>

I share your concern, but I think for clarity we should either 
- Have a script for generating random secrets, not store them in git, and configure hasura & postgres to read those secrets instead of using defaults from the docker images, or
- Explicitly write the default values to secrets files, store them in git and document that they must match the defaults configured in the various docker images.


<!-- Sent from Reviewable.io -->

2021-05-20 09:13 UTC, lassemaatta reviewed
> Reviewed 8 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @haphut, @lassemaatta, and @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-05-20 09:20 UTC, lassemaatta reviewed
As far as I can tell this looks good. 

> Reviewed 2 of 10 files at r5, 6 of 6 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, 1 of 1 files at r19, 2 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-:-Ma83mHIB1-hWg6G7Aac:b-akisdr)* status: all files reviewed, 2 unresolved discussions (waiting on @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-05-24 11:15 UTC, lassemaatta reviewed
I think this is ok (assuming I know how to use reviewable..), but perhaps someone else should also check this out.

> Reviewed 2 of 5 files at r21, 1 of 1 files at r22, 1 of 1 files at r23, 1 of 1 files at r25, 1 of 1 files at r26, 1 of 1 files at r28.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2#-:-MaT4Lg-74wxizwhS4ic:b-e00k6n)* status: all files reviewed, 2 unresolved discussions (waiting on @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-05-26 10:20 UTC, haphut approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: all files reviewed, 1 unresolved discussion (waiting on @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-05-26 10:21 UTC, haphut approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/2)* status: all files reviewed, 1 unresolved discussion (waiting on @tk-vincit)



<!-- Sent from Reviewable.io -->

2021-05-26 13:26 UTC, lassemaatta approved these changes

2021-05-27 12:59 UTC, merged