Change route_shape calculation to use ST_MakeLine
HSLdevcom/jore4-hasura pull request #91
Opened 2022-08-19 10:58 UTC by HenrikHartiala

There are cases when ST_LineMerge & ST_Collect creates a MultiLineString as result, which is preferably not the result what we want. We can use ST_MakeLine to always get LineString as result.

2022-08-19 11:22 UTC, jarkkoka requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala and @jarkkoka)

___
*[`migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91#-N9pozbrAqiByUtKBWrF:-N9pozbrAqiByUtKBWrG:bqkn401) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/28aa5e1f24ba21bbb2c61643eb8a62f3db680603/migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql#L19)):*
> ```TSQL
>         ON (ilar.infrastructure_link_id = il.infrastructure_link_id)
>       ) ON (route_row.route_id = ilar.route_id)
>     WHERE r.route_id = route_row.route_id;
> ```

IMO `ORDER BY ilar.infrastructure_link_sequence` should be added after WHERE predicates in order to guarantee correct order of the infra links.



_Code quote:_
```TSQL
WHERE r.route_id = route_row.route_id;
```


<!-- Sent from Reviewable.io -->

2022-08-19 12:00 UTC, culka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @culka, @HenrikHartiala, and @jarkkoka)

___
*[`migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql` line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91#-N9pw_wkBgjrxXM9l9nL:-N9pw_wkBgjrxXM9l9nM:bvccrv7) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/28aa5e1f24ba21bbb2c61643eb8a62f3db680603/migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql#L3)):*
> ```TSQL
> -- change the route_shape calculating function to use 'ST_MakeLine' to 
> -- get only LineStrings as result of route_shape
> CREATE OR REPLACE FUNCTION route.route_shape(route_row route.route)
> ```

If we want the up and down migrations to be safe and usable from any state, we shouldn't overwrite any existing function.

Rather rename the old function with this migration's timestamp and move it to the deleted schema, like:

```
ALTER FUNCTION route.route_shape(route_row route.route)
    RENAME TO route.route_shape_1660903023968;
    
ALTER FUNCTION route.route_shape_1660903023968(route_row route.route)
    SET SCHEMA deleted;
```
And the down migration should restore the stored function from the deleted -schema.


<!-- Sent from Reviewable.io -->

2022-08-22 09:50 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql` line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91#-N9pw_wkBgjrxXM9l9nL:-NA3vUcL9UAGvyfObL4e:bblc13v) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/28aa5e1f24ba21bbb2c61643eb8a62f3db680603/migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql#L3)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

If we want the up and down migrations to be safe and usable from any state, we shouldn't overwrite any existing function.

Rather rename the old function with this migration's timestamp and move it to the deleted schema, like:

```
ALTER FUNCTION route.route_shape(route_row route.route)
    RENAME TO route.route_shape_1660903023968;
    
ALTER FUNCTION route.route_shape_1660903023968(route_row route.route)
    SET SCHEMA deleted;
```
And the down migration should restore the stored function from the deleted -schema.
</blockquote></details>

Good point! Fixed this
___
*[`migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91#-N9pozbrAqiByUtKBWrF:-NA3vO8L8zzP0AHvAfzI:b804ke9) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/28aa5e1f24ba21bbb2c61643eb8a62f3db680603/migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql#L19)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO `ORDER BY ilar.infrastructure_link_sequence` should be added after WHERE predicates in order to guarantee correct order of the infra links.
</blockquote></details>

Thanks, the ordering is now done inside MakeLine.


<!-- Sent from Reviewable.io -->

2022-08-24 05:37 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91)* status: all files reviewed, 2 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91#-N9q4Hwp9L9bgurVBT5c:-NADLh535RQX0Pkh393s:b-5hynew) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/28aa5e1f24ba21bbb2c61643eb8a62f3db680603/migrations/generic/default/1660903023968_change_route_shape_calculation_to_use_make_line/up.sql#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Minor style issue: extra indent in front of `END`. Should have same amount of indent as `CASE` keyword.
</blockquote></details>

Ah, thanks!


<!-- Sent from Reviewable.io -->

2022-08-24 06:40 UTC, culka approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/91)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)



<!-- Sent from Reviewable.io -->

2022-08-24 06:41 UTC, merged