Perform route verification in one go
HSLdevcom/jore4-hasura pull request #94
Opened 2022-09-06 20:45 UTC by jschummer

2022-09-08 12:58 UTC, jarkkoka requested changes
Data integrity constraints (business rules) and the functions related to implementing them must be more documented with more detail and concrete examples. Please see the comments embedded below.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-:-NBS8fKV0RAemEXLAONp:bio2al7)* status: all files reviewed, 10 unresolved discussions (waiting on @jschummer)

___
*[`integration-test/datasets/prioritizedRouteVerification/journey-patterns.ts` line 110 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBMfou74c-UVHk7klVH:-NBMfou74c-UVHk7klVI:b-5jww1g) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/integration-test/datasets/prioritizedRouteVerification/journey-patterns.ts#L110)):*
> ```XML
>           scheduledStopPointInJourneyPattern.scheduled_stop_point_label ===
>             undefined ||
>           scheduledStopPointInJourneyPattern.scheduled_stop_point_sequence ===
> ```

I think it would be more elegant e.g. to add all these four properties into an array and then call `arr.includes(undefined)`



_Code quote:_
```XML
        if (
          scheduledStopPointInJourneyPattern.scheduled_stop_point_label ===
            undefined ||
          scheduledStopPointInJourneyPattern.scheduled_stop_point_sequence ===
            undefined ||
          scheduledStopPointInJourneyPattern.is_timing_point === undefined ||
          scheduledStopPointInJourneyPattern.is_via_point === undefined
```
___
*[`integration-test/datasets/prioritizedRouteVerification/journey-patterns.ts` line 124 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBMen9F1REzOr3kOr3v:-NBMen9GC5BgAvks4KB7:bsuqw8c) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/integration-test/datasets/prioritizedRouteVerification/journey-patterns.ts#L124)):*
> ```XML
>             scheduledStopPointInJourneyPattern.scheduled_stop_point_label,
>           scheduled_stop_point_sequence:
>             scheduledStopPointInJourneyPattern.scheduled_stop_point_sequence,
> ```

I don't understand why you are copying the fields into a new object (via `Object.assign`) instead of returning just the instance from `scheduledStopPointInJourneyPattern` variable. Could you add a comment here?



_Code quote:_
```XML
        return Object.assign({}, scheduledStopPointInJourneyPattern, {
          journey_pattern_id: journeyPatternOnTempRoute.journey_pattern_id,
          scheduled_stop_point_label:
            scheduledStopPointInJourneyPattern.scheduled_stop_point_label,
          scheduled_stop_point_sequence:
            scheduledStopPointInJourneyPattern.scheduled_stop_point_sequence,
          is_timing_point: scheduledStopPointInJourneyPattern.is_timing_point,
          is_via_point: scheduledStopPointInJourneyPattern.is_via_point,
        });
      },
```
___
*[`integration-test/datasets/prioritizedRouteVerification/routes.ts` line 85 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBMgdz91LG0U757Wcp-:-NBMgdz91LG0U757Wcp0:b4zj23n) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/integration-test/datasets/prioritizedRouteVerification/routes.ts#L85)):*
> ```XML
>         if (
>           infraLinkAlongRoute.infrastructure_link_id === undefined ||
>           infraLinkAlongRoute.infrastructure_link_sequence === undefined ||
> ```

It is a bit mystery to me why exactly these properties need to be checked for `undefined`. What is the reason for that? Why e.g. `route_id` property is not checked?



_Code quote:_
```XML
          infraLinkAlongRoute.infrastructure_link_id === undefined ||
          infraLinkAlongRoute.infrastructure_link_sequence === undefined ||
          infraLinkAlongRoute.is_traversal_forwards === undefined
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 339 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNUoPYB3YtlEBfnC0J:-NBNUoPYB3YtlEBfnC0K:bnewcpb) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L339)):*
> ```TSQL
>            CASE
>              WHEN next_boundary.is_start AND next_boundary.priority > cur_start_priority THEN next_boundary.priority
>              WHEN NOT next_boundary.is_start AND next_boundary.priority >= cur_start_priority THEN 0
> ```

Could not understand the logic of this row.



_Code quote:_
```TSQL
WHEN NOT next_boundary.is_start AND next_boundary.priority >= cur_start_priority THEN 0
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 356 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNUtqDBBsT3arhtx0E:-NBNUtqDBBsT3arhtx0F:bnewcpb) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L356)):*
> ```TSQL
>            CASE
>              WHEN NOT next_boundary.is_start AND next_boundary.priority > cur_end_priority THEN next_boundary.priority
>              WHEN next_boundary.is_start AND next_boundary.priority >= cur_end_priority THEN 0
> ```

Could not understand the logic of this row.



_Code quote:_
```TSQL
WHEN next_boundary.is_start AND next_boundary.priority >= cur_end_priority THEN 0
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 369 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNm_Ud7lFdys9mEdZG:-NBNm_UeBqHFf68KSCQ_:bdbsu1o) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L369)):*
> ```TSQL
>            key2,
>            lead(TRUE, 1, false) OVER entity_window AS has_next,
>            validity_start,
> ```

It is difficult to visualise in mind what kind of results are produced by this subquery. Unfortunately, without concrete data examples, I'm afraid anyone else in the team except the author will be having hard time trying to figure out what is going on here.

The query itself is not very long and it uses some advanced constructs no doubt in a very ingenious way. However, there are multiple recursive queries performed one after the other which makes it really hard for the reviewer to understand the intermediary data results in-between. Without data example commentary for each subquery stage, IMO it is nearly impossible to understand the inner workings of this function. Even some of the simplest data examples would make it much easier to follow the logic.



_Code quote:_
```TSQL
    SELECT key1,
           key2,
           lead(TRUE, 1, false) OVER entity_window AS has_next,
           validity_start,
           lead(validity_start) OVER entity_window AS validity_end
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 384 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNmJU0-fwNcXBMA1Ao:-NBNmJU0-fwNcXBMA1Ap:b-8ei3p4) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L384)):*
> ```TSQL
>     WHERE rb.has_next
>   )
> -- choose the instance with the highest priority for each validity span and
> ```

and what? (sentence not ending properly)



_Code quote:_
```TSQL
and
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 412 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNreuC6gZPb-0xZMet:-NBNreuC6gZPb-0xZMeu:b-rgwb2g) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/mig [...]

2022-09-12 20:40 UTC, jschummer reviewed
Yes, you do have a good point, I can see it's hard to see how things work. I tried to add comments and examples, which I hope make it more easy to understand what is going on.

I've also added unit tests for the `maximum_priority_validity_span` function, so it is tested separately from the "big picture" of the integration test.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-:-NBmHz-L3NanCYdoVczN:b-txp7r4)* status: 1 of 155 files reviewed, 10 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 339 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNUoPYB3YtlEBfnC0J:-NBmF9QUCbmscbVIVnRW:bnpd2a3) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L339)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Could not understand the logic of this row.
</blockquote></details>

In this case, it was noticed during the traversal that the boundary looked at was 1. a validity span end boundary (`NOT is_start`) and 2. its validity span's priority was at least the currently active priority. This means that the boundary closes the currently open validity span. This in turn means that any validity span start boundary following may be significant (by setting `cur_start_priority` to 0 we make sure any next start boundary will be carried on to the next step).

I added more general comments now, which hopefully explain the traversal a bit better.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 356 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNUtqDBBsT3arhtx0E:-NBmFGHA-2sNO17I8ZBU:blbu4wf) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L356)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Could not understand the logic of this row.
</blockquote></details>

This is the corresponding logic of the lines above. The only difference is that this second traversal is done from end to beginning. 

Like mentioned above, I also added general comments, which hopefully explain the traversal a bit better.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 369 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNm_Ud7lFdys9mEdZG:-NBmFJ719XP78pb0-IEX:b-24eguk) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L369)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It is difficult to visualise in mind what kind of results are produced by this subquery. Unfortunately, without concrete data examples, I'm afraid anyone else in the team except the author will be having hard time trying to figure out what is going on here.

The query itself is not very long and it uses some advanced constructs no doubt in a very ingenious way. However, there are multiple recursive queries performed one after the other which makes it really hard for the reviewer to understand the intermediary data results in-between. Without data example commentary for each subquery stage, IMO it is nearly impossible to understand the inner workings of this function. Even some of the simplest data examples would make it much easier to follow the logic.
</blockquote></details>

You do have a good point, it probably is hard to get into the matter without concrete data examples.

I now added a simple data example, which hopefully helps understand what is happening.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 384 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNmJU0-fwNcXBMA1Ao:-NBlkzRKBt-t6BqB1tzx:bipo7fe) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L384)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

and what? (sentence not ending properly)
</blockquote></details>

This was accidentally left in here. Removed it.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 412 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNreuC6gZPb-0xZMet:-NBmIFoiAPOHQ5rnoHL7:b2cap0t) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L412)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This is a good quality commentary!!

However, I was lost in interpreting the data results during the intermediary stages of the query (subquery results). I would have hoped some simple data examples being added for each subquery involved. This way, it would be easier to assess whether the subqueries are doing their job correctly. By documenting the inner workings of the data integrity functions we could lower the risk related to managing all the complex business rules. I cannot overstate how important it is to make data integrity business rules as easily approachable/understandable/transparent as possible.
</blockquote></details>

Yes, I agree, it's just easy to forget these things once you get into the matter... :-)

I now added a simple example which is carried through all steps of the CTE, hopefully that helps.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 792 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNxL9nA69Xg5uWzcBD:-NBlkyPCEfzdC9HCq5Pp:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L792)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

A whitespace missing after `--`. Not a valid SQL comment syntactically. Occurs multiple times in this file.
</blockquote></details>

Done.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 987 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBS0JYT9iUvrLsb8y-S:-NBnNEZ85VfzSGLe3Z9d:b-lu99l0) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L987)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

All of these statement level trigger definitions definitely require a dedicated comment describing why the trigger function needs to be invoked for the table-operation pair, like UPDATE `journey_pattern.journey_pattern` (at least 9 cases in total). E.g. it must be documented why and how deleting a route metadata row (from `route.route` table) would violate data integrity which e.g. is not clear to me as a reviewer. Please explain with examples what specifically could go wrong in each case.

For me as a reviewer, it is not sufficient alone to have SQL code (triggers) that prevents data integrity issues. The errorneous data states must also be enumerated in order to understand why the code is doing what it does.

When business rule documentation (covering data integrity) does not exist or it is too inaccurate we'll get lost with all these complex business rules. IMO this is one of the biggest risks related to our architecture and data model. Everyone in th [...]

2022-09-14 07:39 UTC, jarkkoka approved these changes
Very nice work! It was enlightening to read all those new comments. I personally wasn't aware of of all those invalid states that the triggers prevent. 

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-:-NBun3g03gDjzCgFVqXg:b8qeto1)* status: 2 of 155 files reviewed, 13 unresolved discussions (waiting on @jarkkoka and @jschummer)

___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 412 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNreuC6gZPb-0xZMet:-NBr2dii8lNv17aozN9W:b-acjefc) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L412)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Yes, I agree, it's just easy to forget these things once you get into the matter... :-)

I now added a simple example which is carried through all steps of the CTE, hopefully that helps.
</blockquote></details>

Excellent work in documenting the subqueries of the CTE! Thanks! :1st_place_medal: 
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 987 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBS0JYT9iUvrLsb8y-S:-NBuraJ0EtwqKYVTDvUb:bx6fn27) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L987)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Good point. I've now included a list of all potential ways for the route <-> journey pattern relationship to break with every trigger, hopefully they clear things up.
</blockquote></details>

They do! :+1:  For me it was enlightening to read all these comments. It makes me much more confident about these triggers when all possible invalid states are well documented as well as the implementing functions invoked by the triggers.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1061 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBuowR73tQRo-FRoKyA:-NBuowR73tQRo-FRoKyB:bxzuk0j) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1061)):*
> ```TSQL
>   IS 'Trigger to verify the infra link <-> scheduled stop point references.
>       Updating an infrastructure_link_along_route -row can break the route consistency such that a stop point
>       might be left on an infra link which is not anymore part of its journey pattern''s route.';
> ```

I would rephrase this as:

"Updating an infrastructure_link_along_route -row can break the route consistency in such a way that
an infra link associated with a stop point on a journey pattern might not be part of the (journey pattern''s)
route anymore."



_Code quote:_
```TSQL
      Updating an infrastructure_link_along_route -row can break the route consistency such that a stop point
      might be left on an infra link which is not anymore part of its journey pattern''s route.';
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1072 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBupY2tAc11lk_td7U0:-NBupY2tAc11lk_td7U1:b-cor2m8) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1072)):*
> ```TSQL
>   IS 'Trigger to verify the infra link <-> scheduled stop point references.
>       Deleting an infrastructure_link_along_route -row can break the route consistency such that a stop point
>       might be left on an infra link which is not anymore part of its journey pattern''s route.';
> ```

I would rephrase this as:

"Deleting an infrastructure_link_along_route -row can break the route consistency in such a way that
an infra link associated with a stop point on journey pattern might not be part of the route anymore."



_Code quote:_
```TSQL
      Deleting an infrastructure_link_along_route -row can break the route consistency such that a stop point
      might be left on an infra link which is not anymore part of its journey pattern''s route.';
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1104 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBuqp0g3d3g96zWHeQl:-NBuqp0g3d3g96zWHeQm:b-55nd05) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1104)):*
> ```TSQL
>       3. The updated stop point instance may have "revealed" a lower priority stop point (by change of validity time),
>          which may make the route and journey pattern conflict in the ways described above with regards to the revealed
>          stop point.
> ```

Typo. You should always use: "with regard to"



_Code quote:_
```TSQL
with regards to
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1117 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBurHxHBHWC9nP6NJm4:-NBurHxHBHWC9nP6NJm5:bc4q30f) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1117)):*
> ```TSQL
>   IS 'Trigger to verify the infra link <-> scheduled stop point references.
>       Deleting a scheduled_stop_point instance can break the route consistency in the following ways:
>       1. The updated stop point instance may have "revealed" a lower priority stop point, which may make the route and
> ```

The deleted stop point instance may "reveal" a lower priority stop point instance



_Code quote:_
```TSQL
The updated stop point instance may have "revealed" a lower priority stop point
```
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1133 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NButgbT0jDBOjJT6Vss:-NButgbT0jDBOjJT6Vst:b-khypf0) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1133)):*
> ```TSQL
>   IS 'Trigger to verify the infra link <-> scheduled stop point references.
>       Updating a journey_pattern row can break the route consistency in the way that the updated journey pattern is
>       moved to a route, such that
> ```

I would rephrase this as:

"Updating a journey_pattern''s reference to route (`on_route_id`) can break the route consistency in a way that
the new route is in violation with the journey pattern''s stop points in one of the following ways:"

I think it needs to be highlighted here that the `on_route_id` is the only field that can be a source of issues since `journey_pattern` is just a metadata table anyway.



_Code quote:_
```TSQL
      Updating a journey_pattern row can break the route consistency in the way that the updated journey pattern is
      moved to a route, such that
```


<!-- Sent from Reviewable.io -->

2022-09-15 07:42 UTC, jschummer reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94)* status: 1 of 155 files reviewed, 12 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 412 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBNreuC6gZPb-0xZMet:-NBzx9TV5djQlUUA2VK0:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L412)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Excellent work in documenting the subqueries of the CTE! Thanks! :1st_place_medal: 
</blockquote></details>

Done.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 987 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBS0JYT9iUvrLsb8y-S:-NC-35VvCdlNspOTdwgx:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/c527b42a24f04e26ea460084339c39362f1bf97f/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L987)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

They do! :+1:  For me it was enlightening to read all these comments. It makes me much more confident about these triggers when all possible invalid states are well documented as well as the implementing functions invoked by the triggers.
</blockquote></details>

Done.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1061 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBuowR73tQRo-FRoKyA:-NC-3kni3dP5UHV1U2OE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1061)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would rephrase this as:

"Updating an infrastructure_link_along_route -row can break the route consistency in such a way that
an infra link associated with a stop point on a journey pattern might not be part of the (journey pattern''s)
route anymore."
</blockquote></details>

Done.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1072 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBupY2tAc11lk_td7U0:-NC-2pLz8jLLerK9d4rE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1072)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would rephrase this as:

"Deleting an infrastructure_link_along_route -row can break the route consistency in such a way that
an infra link associated with a stop point on journey pattern might not be part of the route anymore."
</blockquote></details>

Done.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1117 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NBurHxHBHWC9nP6NJm4:-NC-343ZDEOvWq6UIZyz:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1117)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The deleted stop point instance may "reveal" a lower priority stop point instance
</blockquote></details>

Done.
___
*[`migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql` line 1133 at r6](https://reviewable.io/reviews/hsldevcom/jore4-hasura/94#-NButgbT0jDBOjJT6Vss:-NC-3SGS1bgd7YPNCz3b:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5802ebe42af0ebf053d36cbcc92f5b5ac4cc09c0/migrations/generic/default/1661496355072_perform_route_verification_in_one_go/up.sql#L1133)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would rephrase this as:

"Updating a journey_pattern''s reference to route (`on_route_id`) can break the route consistency in a way that
the new route is in violation with the journey pattern''s stop points in one of the following ways:"

I think it needs to be highlighted here that the `on_route_id` is the only field that can be a source of issues since `journey_pattern` is just a metadata table anyway.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-15 07:43 UTC, merged